### ISSUE TITLE
I can't launch the game with Steam open

### ISSUE THREAD

**Issue by kassai-g** [aclist/dztui#10]
Dear Creator!

Your launcher is a gift to us players, thank you very much for making it. It was working for me perfectly until a few days ago, when I had a strange problem: the game only starts if I exit Steam then I launch the game from your script. Also, sometimes when I try to download mods, the steamcmd tells me that it can't download the mod because of no storage.

I even tried launching the game with terminal like this, and this is what I get from the terminal as a response.

steam -applaunch 221100 -connect=168.100.161.234:2302 -nolauncher -nosplash -skipintro "-mod=@1602372402-DeerIsle;@2490100317-Rearmed_Server_Pack;@2762521201-BuildingsModPack7;@2502755029-BuildingsModPack6;@2323220044-BuildingsModPack5;@1710977250-BaseBuildingPlus;@2646817942-Tactical_Flava;@2709289485-Admirals_Diving_Mod;@2757080411-Croco_s_Quadbike;@2501812949-Flying_Birds;@2384407442-ZStuff;@2393499239-TerrainIslands;@1832448183-FlipTransport;@2358569462-IndustrialModPack;@2307297070-BuildingsMegaModPack;@2545980712-Custom_animations;@2576460232-DayZ_Expansion_Name_Tags;@2572328470-DayZ_Expansion_Market;@2291785308-DayZ_Expansion_Core;@2692979668-RedFalcon_Flight_System_Heliz;@1828439124-VPPAdminTools;@2491484149-Helicrash_Licensed;@2449234595-Mag_Obfuscation;@2444301292-Care_Packages;@2545327648-Dabs_Framework;@2276010135-DayZ_Editor_Loader;@2604031635-AutoTransmissions;@2786677604-Survivalists_FacePaints;@2444247391-Inventory_Move_Sounds;@2303554682-Dogtags;@2303483532-CarCover;@2049002856-MuchCarKey;@1827241477-Breachingcharge;@1646187754-Code_Lock;@1797720064-WindstridesClothingPack;@1991570984-MuchStuffPack;@1630943713-Cl0ud_s_Military_Gear;@1559212036-CF;@-;@-"

steam.sh[33915]: Running Steam on manjarolinux 21.2.6 64-bit
steam.sh[33915]: STEAM_RUNTIME is enabled automatically
setup.sh[33989]: Steam runtime environment up-to-date!
steam.sh[33915]: Steam client's requirements are satisfied

After I see this message, nothing happens.

**Comment by kassai-g** [comment]
steam -applaunch 221100 -connect=168.100.161.234:2302 -nolauncher -nosplash -skipintro "-mod=@1602372402-DeerIsle;@2490100317-Rearmed_Server_Pack;@2762521201-BuildingsModPack7;@2502755029-BuildingsModPack6;@2323220044-BuildingsModPack5;@1710977250-BaseBuildingPlus;@2646817942-Tactical_Flava;@2709289485-Admirals_Diving_Mod;@2757080411-Croco_s_Quadbike;@2501812949-Flying_Birds;@2384407442-ZStuff;@2393499239-TerrainIslands;@1832448183-FlipTransport;@2358569462-IndustrialModPack;@2307297070-BuildingsMegaModPack;@2545980712-Custom_animations;@2576460232-DayZ_Expansion_Name_Tags;@2572328470-DayZ_Expansion_Market;@2291785308-DayZ_Expansion_Core;@2692979668-RedFalcon_Flight_System_Heliz;@1828439124-VPPAdminTools;@2491484149-Helicrash_Licensed;@2449234595-Mag_Obfuscation;@2444301292-Care_Packages;@2545327648-Dabs_Framework;@2276010135-DayZ_Editor_Loader;@2604031635-AutoTransmissions;@2786677604-Survivalists_FacePaints;@2444247391-Inventory_Move_Sounds;@2303554682-Dogtags;@2303483532-CarCover;@2049002856-MuchCarKey;@1827241477-Breachingcharge;@1646187754-Code_Lock;@1797720064-WindstridesClothingPack;@1991570984-MuchStuffPack;@1630943713-Cl0ud_s_Military_Gear;@1559212036-CF;@-;@-"
steam.sh[38050]: Running Steam on manjarolinux 21.2.6 64-bit
steam.sh[38050]: STEAM_RUNTIME is enabled automatically
setup.sh[38124]: Steam runtime environment up-to-date!
steam.sh[38050]: Steam client's requirements are satisfied
[2022-05-07 16:11:45] Startup - updater built Mar 14 2022 19:48:46
Installing breakpad exception handler for appid(steam)/version(1647446817)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2022-05-07 16:11:45] Loading cached metrics from disk (/home/kassaig/.local/share/Steam/package/steam_client_metrics.bin)
[2022-05-07 16:11:45] Using the following download hosts for Public, Realm steamglobal
[2022-05-07 16:11:45] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-05-07 16:11:45] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-05-07 16:11:45] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1647446817)
[2022-05-07 16:11:45] Checking for update on startup
[2022-05-07 16:11:45] Checking for available updates...
[2022-05-07 16:11:45] Downloading manifest: https://cdn.cloudflare.steamstatic.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1647446817)
[2022-05-07 16:11:46] Download skipped: /client/steam_client_ubuntu12 version 1647446817, installed version 1647446817, existing pending version 0
[2022-05-07 16:11:46] Nothing to do
[2022-05-07 16:11:46] Verifying installation...
[2022-05-07 16:11:46] Performing checksum verification of executable files
[2022-05-07 16:11:46] Verification complete
Loaded SDL version 2.0.21-7140709
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'

(steam:38188): Gtk-WARNING **: 16:11:46.925: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
steamwebhelper.sh[38209]: Runtime for steamwebhelper: defaulting to /home/kassaig/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Installing breakpad exception handler for appid(steam)/version(1647446817)
steamwebhelper.sh[38209]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
CAppInfoCacheReadFromDiskThread took 32 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)

(steam:38188): Gtk-WARNING **: 16:11:47.784: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1647446817)
Connectivity test: result=Connected, in progress=0
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
roaming config store loaded successfully - 550 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 6ms
Installing breakpad exception handler for appid(steam)/version(1647446817)
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/kassaig/.local/share/Steam/ubuntu12_32/steam' '-applaunch' '221100' '-connect=168.100.161.234:2302' '-nolauncher' '-nosplash' '-skipintro' '-mod=@1602372402-DeerIsle;@2490100317-Rearmed_Server_Pack;@2762521201-BuildingsModPack7;@2502755029-BuildingsModPack6;@2323220044-BuildingsModPack5;@1710977250-BaseBuildingPlus;@2646817942-Tactical_Flava;@2709289485-Admirals_Diving_Mod;@2757080411-Croco_s_Quadbike;@2501812949-Flying_Birds;@2384407442-ZStuff;@2393499239-TerrainIslands;@1832448183-FlipTransport;@2358569462-IndustrialModPack;@2307297070-BuildingsMegaModPack;@2545980712-Custom_animations;@2576460232-DayZ_Expansion_Name_Tags;@2572328470-DayZ_Expansion_Market;@2291785308-DayZ_Expansion_Core;@2692979668-RedFalcon_Flight_System_Heliz;@1828439124-VPPAdminTools;@2491484149-Helicrash_Licensed;@2449234595-Mag_Obfuscation;@2444301292-Care_Packages;@2545327648-Dabs_Framework;@2276010135-DayZ_Editor_Loader;@2604031635-AutoTransmissions;@2786677604-Survivalists_FacePaints;@2444247391-Inventory_Move_Sounds;@2303554682-Dogtags;@2303483532-CarCover;@2049002856-MuchCarKey;@1827241477-Breachingcharge;@1646187754-Code_Lock;@1797720064-WindstridesClothingPack;@1991570984-MuchStuffPack;@1630943713-Cl0ud_s_Military_Gear;@1559212036-CF;@-;@-'"
System startup time: 3.30 seconds
GameAction [AppID 221100, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
BuildCompleteAppOverviewChange: 138

(steam:38188): Gtk-WARNING **: 16:11:50.818: gtk_disable_setlocale() must be called before gtk_init()

(steam:38188): GLib-CRITICAL **: 16:11:50.820: unquote_string_inplace: assertion 'err == NULL || *err == NULL' failed
RegisterForAppOverview 1: 12ms
RegisterForAppOverview 2: 12ms

(steam:38188): Gtk-WARNING **: 16:11:51.324: gtk_disable_setlocale() must be called before gtk_init()

(steam:38188): GLib-CRITICAL **: 16:11:51.324: unquote_string_inplace: assertion 'err == NULL || *err == NULL' failed
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Installing breakpad exception handler for appid(steam)/version(1647446817)
GameAction [AppID 221100, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 221100, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 221100, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 221100, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 221100, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/kassaig/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=221100 -- '/home/kassaig/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kassaig/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/home/kassaig/.local/share/Steam/steamapps/common/DayZ/DayZLauncher.exe' '-connect=168.100.161.234:2302' '-nolauncher' '-nosplash' '-skipintro' '-mod=@1602372402-DeerIsle;@2490100317-Rearmed_Server_Pack;@2762521201-BuildingsModPack7;@2502755029-BuildingsModPack6;@2323220044-BuildingsModPack5;@1710977250-BaseBuildingPlus;@2646817942-Tactical_Flava;@2709289485-Admirals_Diving_Mod;@2757080411-Croco_s_Quadbike;@2501812949-Flying_Birds;@2384407442-ZStuff;@2393499239-TerrainIslands;@1832448183-FlipTransport;@2358569462-IndustrialModPack;@2307297070-BuildingsMegaModPack;@2545980712-Custom_animations;@2576460232-DayZ_Expansion_Name_Tags;@2572328470-DayZ_Expansion_Market;@2291785308-DayZ_Expansion_Core;@2692979668-RedFalcon_Flight_System_Heliz;@1828439124-VPPAdminTools;@2491484149-Helicrash_Licensed;@2449234595-Mag_Obfuscation;@2444301292-Care_Packages;@2545327648-Dabs_Framework;@2276010135-DayZ_Editor_Loader;@2604031635-AutoTransmissions;@2786677604-Survivalists_FacePaints;@2444247391-Inventory_Move_Sounds;@2303554682-Dogtags;@2303483532-CarCover;@2049002856-MuchCarKey;@1827241477-Breachingcharge;@1646187754-Code_Lock;@1797720064-WindstridesClothingPack;@1991570984-MuchStuffPack;@1630943713-Cl0ud_s_Military_Gear;@1559212036-CF;@-;@-' -nolauncher -nosplash -skipintro\0
Game process added : AppID 221100 "/home/kassaig/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=221100 -- '/home/kassaig/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kassaig/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/home/kassaig/.local/share/Steam/steamapps/common/DayZ/DayZLauncher.exe' '-connect=168.100.161.234:2302' '-nolauncher' '-nosplash' '-skipintro' '-mod=@1602372402-DeerIsle;@2490100317-Rearmed_Server_Pack;@2762521201-BuildingsModPack7;@2502755029-BuildingsModPack6;@2323220044-BuildingsModPack5;@1710977250-BaseBuildingPlus;@2646817942-Tactical_Flava;@2709289485-Admirals_Diving_Mod;@2757080411-Croco_s_Quadbike;@2501812949-Flying_Birds;@2384407442-ZStuff;@2393499239-TerrainIslands;@1832448183-FlipTransport;@2358569462-IndustrialModPack;@2307297070-BuildingsMegaModPack;@2545980712-Custom_animations;@2576460232-DayZ_Expansion_Name_Tags;@2572328470-DayZ_Expansion_Market;@2291785308-DayZ_Expansion_Core;@2692979668-RedFalcon_Flight_System_Heliz;@1828439124-VPPAdminTools;@2491484149-Helicrash_Licensed;@2449234595-Mag_Obfuscation;@2444301292-Care_Packages;@2545327648-Dabs_Framework;@2276010135-DayZ_Editor_Loader;@2604031635-AutoTransmissions;@2786677604-Survivalists_FacePaints;@2444247391-Inventory_Move_Sounds;@2303554682-Dogtags;@2303483532-CarCover;@2049002856-MuchCarKey;@1827241477-Breachingcharge;@1646187754-Code_Lock;@1797720064-WindstridesClothingPack;@1991570984-MuchStuffPack;@1630943713-Cl0ud_s_Military_Gear;@1559212036-CF;@-;@-' -nolauncher -nosplash -skipintro", ProcID 38684, IP 0.0.0.0:0
chdir /home/kassaig/.local/share/Steam/steamapps/common/DayZ
ERROR: ld.so: object '/home/kassaig/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kassaig/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kassaig/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kassaig/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kassaig/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 38688 != 38685, skipping destruction (fork without exec?)
GameAction [AppID 221100, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 221100, ActionID 1] : LaunchApp changed task to Completed with ""
Installing breakpad exception handler for appid(steam)/version(1647446817)
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
ThreadGetProcessExitCode: no such process 38861
ThreadGetProcessExitCode: no such process 38859
ThreadGetProcessExitCode: no such process 38686
ThreadGetProcessExitCode: no such process 38864
Game process updated : AppID 221100 "/home/kassaig/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=221100 -- '/home/kassaig/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kassaig/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/home/kassaig/.local/share/Steam/steamapps/common/DayZ/DayZLauncher.exe' '-connect=168.100.161.234:2302' '-nolauncher' '-nosplash' '-skipintro' '-mod=@1602372402-DeerIsle;@2490100317-Rearmed_Server_Pack;@2762521201-BuildingsModPack7;@2502755029-BuildingsModPack6;@2323220044-BuildingsModPack5;@1710977250-BaseBuildingPlus;@2646817942-Tactical_Flava;@2709289485-Admirals_Diving_Mod;@2757080411-Croco_s_Quadbike;@2501812949-Flying_Birds;@2384407442-ZStuff;@2393499239-TerrainIslands;@1832448183-FlipTransport;@2358569462-IndustrialModPack;@2307297070-BuildingsMegaModPack;@2545980712-Custom_animations;@2576460232-DayZ_Expansion_Name_Tags;@2572328470-DayZ_Expansion_Market;@2291785308-DayZ_Expansion_Core;@2692979668-RedFalcon_Flight_System_Heliz;@1828439124-VPPAdminTools;@2491484149-Helicrash_Licensed;@2449234595-Mag_Obfuscation;@2444301292-Care_Packages;@2545327648-Dabs_Framework;@2276010135-DayZ_Editor_Loader;@2604031635-AutoTransmissions;@2786677604-Survivalists_FacePaints;@2444247391-Inventory_Move_Sounds;@2303554682-Dogtags;@2303483532-CarCover;@2049002856-MuchCarKey;@1827241477-Breachingcharge;@1646187754-Code_Lock;@1797720064-WindstridesClothingPack;@1991570984-MuchStuffPack;@1630943713-Cl0ud_s_Military_Gear;@1559212036-CF;@-;@-' -nolauncher -nosplash -skipintro", ProcID 38860, IP 0.0.0.0:0
Setting breakpad minidump AppID = 221100
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198315857766 [API loaded no]
ThreadGetProcessExitCode: no such process 38935
ThreadGetProcessExitCode: no such process 38904
Game process updated : AppID 221100 "/home/kassaig/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=221100 -- '/home/kassaig/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kassaig/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/home/kassaig/.local/share/Steam/steamapps/common/DayZ/DayZLauncher.exe' '-connect=168.100.161.234:2302' '-nolauncher' '-nosplash' '-skipintro' '-mod=@1602372402-DeerIsle;@2490100317-Rearmed_Server_Pack;@2762521201-BuildingsModPack7;@2502755029-BuildingsModPack6;@2323220044-BuildingsModPack5;@1710977250-BaseBuildingPlus;@2646817942-Tactical_Flava;@2709289485-Admirals_Diving_Mod;@2757080411-Croco_s_Quadbike;@2501812949-Flying_Birds;@2384407442-ZStuff;@2393499239-TerrainIslands;@1832448183-FlipTransport;@2358569462-IndustrialModPack;@2307297070-BuildingsMegaModPack;@2545980712-Custom_animations;@2576460232-DayZ_Expansion_Name_Tags;@2572328470-DayZ_Expansion_Market;@2291785308-DayZ_Expansion_Core;@2692979668-RedFalcon_Flight_System_Heliz;@1828439124-VPPAdminTools;@2491484149-Helicrash_Licensed;@2449234595-Mag_Obfuscation;@2444301292-Care_Packages;@2545327648-Dabs_Framework;@2276010135-DayZ_Editor_Loader;@2604031635-AutoTransmissions;@2786677604-Survivalists_FacePaints;@2444247391-Inventory_Move_Sounds;@2303554682-Dogtags;@2303483532-CarCover;@2049002856-MuchCarKey;@1827241477-Breachingcharge;@1646187754-Code_Lock;@1797720064-WindstridesClothingPack;@1991570984-MuchStuffPack;@1630943713-Cl0ud_s_Military_Gear;@1559212036-CF;@-;@-' -nolauncher -nosplash -skipintro", ProcID 38942, IP 0.0.0.0:0
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
wine: Unhandled page fault on read access to 0000000000000048 at address 00000001402DFF14 (thread 0158), starting debugger...
ThreadGetProcessExitCode: no such process 38998
ThreadGetProcessExitCode: no such process 38917
ThreadGetProcessExitCode: no such process 38898
ThreadGetProcessExitCode: no such process 38892
ThreadGetProcessExitCode: no such process 38869
ThreadGetProcessExitCode: no such process 38866
ThreadGetProcessExitCode: no such process 38860
ThreadGetProcessExitCode: no such process 38858
pid 38862 != 38861, skipping destruction (fork without exec?)
Game process removed: AppID 221100 "/home/kassaig/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=221100 -- '/home/kassaig/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kassaig/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/home/kassaig/.local/share/Steam/steamapps/common/DayZ/DayZLauncher.exe' '-connect=168.100.161.234:2302' '-nolauncher' '-nosplash' '-skipintro' '-mod=@1602372402-DeerIsle;@2490100317-Rearmed_Server_Pack;@2762521201-BuildingsModPack7;@2502755029-BuildingsModPack6;@2323220044-BuildingsModPack5;@1710977250-BaseBuildingPlus;@2646817942-Tactical_Flava;@2709289485-Admirals_Diving_Mod;@2757080411-Croco_s_Quadbike;@2501812949-Flying_Birds;@2384407442-ZStuff;@2393499239-TerrainIslands;@1832448183-FlipTransport;@2358569462-IndustrialModPack;@2307297070-BuildingsMegaModPack;@2545980712-Custom_animations;@2576460232-DayZ_Expansion_Name_Tags;@2572328470-DayZ_Expansion_Market;@2291785308-DayZ_Expansion_Core;@2692979668-RedFalcon_Flight_System_Heliz;@1828439124-VPPAdminTools;@2491484149-Helicrash_Licensed;@2449234595-Mag_Obfuscation;@2444301292-Care_Packages;@2545327648-Dabs_Framework;@2276010135-DayZ_Editor_Loader;@2604031635-AutoTransmissions;@2786677604-Survivalists_FacePaints;@2444247391-Inventory_Move_Sounds;@2303554682-Dogtags;@2303483532-CarCover;@2049002856-MuchCarKey;@1827241477-Breachingcharge;@1646187754-Code_Lock;@1797720064-WindstridesClothingPack;@1991570984-MuchStuffPack;@1630943713-Cl0ud_s_Military_Gear;@1559212036-CF;@-;@-' -nolauncher -nosplash -skipintro", ProcID 38942 
ThreadGetProcessExitCode: no such process 38942
ThreadGetProcessExitCode: no such process 38878
ThreadGetProcessExitCode: no such process 38685
Game 221100 created interface STEAMAPPLIST_INTERFACE_VERSION001 / AppList
Game 221100 created interface STEAMAPPS_INTERFACE_VERSION008 / Apps
Game 221100 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_004 / HTMLSurface
Game 221100 created interface STEAMHTTP_INTERFACE_VERSION002 / HTTP
Game 221100 created interface STEAMINVENTORY_INTERFACE_V002 / Inventory
Game 221100 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
Game 221100 created interface STEAMMUSIC_INTERFACE_VERSION001 / Music
Game 221100 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
Game 221100 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
Game 221100 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
Game 221100 created interface STEAMUGC_INTERFACE_VERSION010 / UGC
Game 221100 created interface STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001 / UnifiedMessages
Game 221100 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
Game 221100 created interface STEAMVIDEO_INTERFACE_V002 / Video
Game 221100 created interface SteamController005 / Controller
Game 221100 created interface SteamFriends015 / Friends
Game 221100 created interface SteamMatchMaking009 / Matchmaking
Game 221100 created interface SteamMatchMakingServers002 / MatchmakingServers
Game 221100 created interface SteamNetworking005 / Networking
Game 221100 created interface SteamUser019 / User
Game 221100 created interface SteamUtils009 / Utils
Game 221100 method call count for IClientAppManager::BIsDlcEnabled : 2
Game 221100 method call count for IClientAppManager::IsAppDlcInstalled : 3
Game 221100 method call count for IClientApps::BGetDLCDataByIndex : 2
Game 221100 method call count for IClientApps::GetDLCCount : 1
Game 221100 method call count for IClientUtils::RecordSteamInterfaceCreation : 23
Game 221100 method call count for IClientUtils::GetAppID : 24
Game 221100 method call count for IClientUtils::GetIPCountry : 1
Game 221100 method call count for IClientUser::BIsSubscribedApp : 3
Game 221100 method call count for IClientUser::GetSteamID : 3
Game 221100 method call count for IClientUser::BLoggedOn : 1
Uploaded AppInterfaceStats to Steam

This is how the terminal looks like when I launch the game without Steam. It works only this way.

Also, I have a game script compile error now when I join a server.

**Comment by aclist** [comment]
Thanks for the logs. I haven't launched DayZ in a little while, but I don't believe anything has changed upstream. This sounds like it might be a local system setting or a steamcmd/mod config error that is causing a situation we don't have proper error handling for in the script. I will try to reproduce your error. 

In the second log, it looks like wine is actually crashing, so it's kind of strange that the game proceeds after that.

Can you please provide the following?

1. Version of Proton being used
2. Whether you are on the Steam beta branch
3. Whether this happens on every server
4. Are you using the latest version (`0.3.0`) of the script?
5. Are you using the `steam` package or `steam-runtime`?
6. Did you define any additional launch options for the game in Steam?

Also, to eliminate other possibilities, please try:

1. Other Proton versions
2. Connecting to other servers
3. Starting Steam and the script from a clean session/shell
4. Backing up your mods directory and connecting with a clean setup <-- important
5. Reinstalling steamcmd and clearing steamcmd configs <-- important

>> Also, sometimes when I try to download mods, the steamcmd tells me that it can't download the mod because of no storage.

Next time this happens, please provide logs if possible. Do you in fact have enough storage?

>> Also, I have a game script compile error now when I join a server.

Same as above. This sounds more localized to a specific server/mod. I don't think servers provide checksums of installed mods, so we can't verify integrity of mods every time without redownloading them. Again, I would recommend clearing out your mods and attempting to connect on a vanilla setup to try to recreate the mods cleanly.

**Comment by kassai-g** [comment]
Thank you for your quick response.

1. I use Proton 7.0-2.
2. I don't use the Steam beta branch.
3. This error happens on every modded server.
4. Yes, I use 0.3.0, and it worked like magic :)
5. I have Steam installed from their official website, but when I type **steam** and **steam-runtime** in the terminal, both "work". I will provide a log for the output of running them in the terminal. I use the shortcut that leads me to Steam (Runtime).
6. The additional launch options are: -nolauncher -nosplash -skipintro. I have also set the vm.max_map_count=1048576.

So I managed to fix the game script compile error, turned out every 1 in 10 people had it on the server I play on. I also have a spare storage space of 250GB, so that is likely not a problem.

However, I still can't play Dayz with Steam already open, and this wasn't the case 3 days ago.

https://pastebin.com/gjfPJ4W6 - for the **steam** output in terminal
https://pastebin.com/CHhJeLuB - for the **steam-runtime** output in terminal
(I closed them after running the test for output)

Thank you very much for reading this, have a beautiful day!

**Comment by aclist** [comment]
I finished working on another compatibility report, so I'm focusing on this now. My initial observation is that the DayZ depots were updated 7+ days ago, but the problem manifested itself approximately 4 days ago for you, so I don't think it's a change to the game itself.

I tested on my end and was able to launch into modded servers directly with Steam running as usual. 

Can you double-check in your DayZ right-click settings that Proton is actually selected as the compatibility layer? When testing, I noticed that my DayZ configs (not changed since I last played) had reverted to the Linux version due to some Steam update, so it was defaulting to trying to run the Linux blob instead of the Windows version through Proton. Once I reverted to Proton, it worked again. 

I noticed that you said you installed Steam from their web site. This is a bit unorthodox. Is there a reason you didn't install it from your package manager? Is that something you did recently? I'm wondering if you are in fact launching two versions of the Steam client: one by default with your login session, and a different Steam version via the script.

You also don't need to manually add launch options. These are concatenated by DZTUI itself at runtime. 

None of these things is extremely important, but I'm trying to establish a level basis for troubleshooting here, since there are some weird things going on with your configuration.

The only other thing that comes to mind right now is that the `-applaunch` method of interfacing with the Steam executable directly, although supported, is less robust than the [Steam browser protocol](https://developer.valvesoftware.com/wiki/Steam_browser_protocol). The reason DZTUI uses it is it gives better control over passing complex command line options through simple quoting versus the URI method, which is really strict about the way inputs are sanitized.

I'd recommend establishing a baseline by clearing out the configs mentioned above and using Steam from your distro's package manager: verify that it's working with the bare minimum setup first.

As for steamcmd warnings, that tool is a bit experimental and isn't well-maintained or documented. I would recommend running it standalone to "initialize" the internal configs and point it to the right drives before using it in conjunction with DZTUI. Incidentally, DZTUI writes mods to the `/tmp` dir only when downloading through steamcmd, but steamcmd may have some defaults built in where it's trying to install to the wrong place. The `+force_install_dir` switch we are passing to steamcmd forces it to override the default install path.

Keep in mind that the auto-mod install mode is experimental because we depend on the behavior of steamcmd here. You could try dropping down to the manual mode to see if this reduces false positives.

I'll keep trying to reproduce your error here in case it affects other users. You should continue smoke testing and trying to break things to narrow down what might be causing it.

**Comment by kassai-g** [comment]
Okay, so I don't know what happened, but I had a Steam update and it magically solved itself. I suppose case can be closed now.

**Comment by aclist** [comment]
Thanks for updating. There have been some problems with Steam's authentication servers recently, preventing games from synchronizing and launching. If you were already logged in during this time, it might have manifested itself as a launch problem. If you logged out during this time, you might have been unable to log back in. I can't say for sure, but it seems like it was an ephemeral problem.

**Comment by aclist** [comment]
Hi, this was recently tracked down to a bug in the Steam client and servers with a large number of mods. It is fixed now in the latest version of DZTUi.

**Comment by aclist** [comment]
A fix for this is now available in the Testing branch of DZGUI and will roll out to the Stable branch of DZGUI soon.
