### ISSUE TITLE
Connection Failed 0x00020009

### ISSUE THREAD

**Issue by mkarenko** [aclist/dztui#102]
Ubuntu 23.10
CPU Ryzen 1600
GPU RX580
Steam from dpkg
Today I borrowed an account from a friend with a game, downloaded it, put in the magical command sysctl -w vm.max_map_count=1048576, launched it, and to my surprise, the game worked. I decided to buy it (an 11-year-old game that originally cost €24, now on sale for €22.55 XDDD). I bought it, didn't have to download it again, and decided to install dzgui. Everything went smoothly, didn't have to fix anything, mods were read, the game launched. Unfortunately, the problem is as follows: when I try to enter the game, I get error 0x00020009 Connection Failed.
Does anyone have any idea what's going on?
I tried to delete 3 folders of dzgui, dayz and download again.

![image](https://github.com/aclist/dztui/assets/71224089/f8c56c5f-35e3-4d6e-bf4f-83a852e364db)

**Comment by aclist** [comment]
It seems to be a bug in DayZ Experimental servers: https://feedback.bistudio.com/T175914

Possible workarounds are discussed here:

1. https://old.reddit.com/r/dayz/comments/173sgs1/dayz_123156797_exp_failure_to_connect_0x00020009/

2. https://www.youtube.com/watch?v=tigiFNunexg

3. https://old.reddit.com/r/dayz/comments/o29lsq/0x00020009_connection_failed/

It may be related to networking settings (are you using Wi-Fi?), or may be related to an implementation in the Experimental server protocol. Have you tried connecting to non-Experimental servers?

It's not an issue on DZGUI's side.

**Comment by mkarenko** [comment]
Hey, thanks for links I did try everything, even deleted profile data. Still no success.
- Im on cable normally
- tried wi-fi
- tried hotspot from my phone
- tried everything above with vpn
- tried to flash dns
- 
Anyway if it's not problem with dzgui I'll close the issue as resolved. One more question does anyone know where is something like AppData of linux, I want to manually look for dayz profile save folder.

**Comment by mkarenko** [comment]
One more question, what do you mean by DayZ Experimental server? I'm trying to connect via in-game server lobby.

**Comment by sideiron** [comment]
Today i can no longer join servers either. I did notice proton updates this morning which might have done something? Played fine all day yesterday. Proton experimental was working until today for me. Tried the Proton 9 beta and could not join a server. Got the 0200009 error every try.

**Comment by mkarenko** [comment]
I got it to work, I changed to proton from experimental to 8.0-5. And belive me when I say I tried everything. This step I tried last. Now I will try to get it work with dzgui. Nevertheless thanks for help.
![image](https://github.com/aclist/dztui/assets/71224089/9aa706b6-0ed7-416a-8d31-84aac66f5c9f)
![image](https://github.com/aclist/dztui/assets/71224089/f038092d-2346-4dec-a06c-2835a49b2467)

**Comment by sideiron** [comment]
Thank you this worked for me.

**Comment by aclist** [comment]
> One more question does anyone know where is something like AppData of linux, I want to manually look for dayz profile save folder.

DayZ is installed under `<Steam Install Path>/steamapps/common/DayZ`. The Wine prefix is installed under `<Steam Install Path>/steamapps/compatdata/221100`, so the same directory hierarchy as Windows applies:

`<Steam Install Path>/steamapps/compatdata/221100/pfx/drive_c/users/steamuser/AppData/Local/DayZ`

> One more question, what do you mean by DayZ Experimental server? I'm trying to connect via in-game server lobby.

DayZ Experimental is an alternate build provided by Bohemia that some servers run on. It looks like it was not related in this case.

> I got it to work, I changed to proton from experimental to 8.0-5. 

Thank you for the update. I suggest finding a stable version of Proton that works for you and staying with it, or trying Proton-GE in the future rather than Proton Experimental.
