### ISSUE TITLE
Failed to installed due to missing module named "gi"

### ISSUE THREAD

**Issue by andersfylling** [aclist/dztui#104]
I'm running arch linux 6.8.1-arch1-1 and I have installed the dependencies: `curl`, `jq`, `zenity`, `steam`, `wmctrl`. When I try to install dzgui via `curl -s "https://raw.githubusercontent.com/aclist/dztui/dzgui/install.sh" | bash` I get the output:

```
➜  ~ curl -s "https://raw.githubusercontent.com/aclist/dztui/dzgui/install.sh" | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26028  100 26028    0     0  1474k      0 --:--:-- --:--:-- --:--:-- 1495k
Initializing setup...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
```

I am also presented with a modal:
![image](https://github.com/aclist/dztui/assets/7851860/a442d407-50b4-4690-af30-b6fa2b738967)

**Comment by aclist** [comment]
You must install this package: https://archlinux.org/packages/extra/x86_64/python-gobject/

Sorry about the documentation; I am currently rewriting it to reflect changes in version 5.0.0, so the section you referred to is slightly out of date. The new DZGUI UI uses GTK bindings through Python and requires the package mentioned in the modal. (Variously called `python-gobject` or `python3-gobject` on different distributions)

**Comment by andersfylling** [comment]
No worries, can confirm that installing python-gobject solved the issue for me. I'll leave the issue here so you can chose to close it now or when you've updated the docs

**Comment by aclist** [comment]
Thank you. I updated the documentation regarding dependencies on the day you submitted this ticket, but the full documentation update will be coming in about a week.
