### ISSUE TITLE
When I load into my server list or recent servers nothing shows up

### ISSUE THREAD

**Issue by Njmooer** [aclist/dztui#139]
Pretty much the title it ends up all blank

**Comment by aclist** [comment]
Please provide the following information:

- DZGUI version
- Stable or testing branch
- PC or Steam Deck
- Wi-Fi or wired ethernet
- Name/IP of server you tried to connect to
- Steps leading up to the problem
- Copy of the `DZGUI_DEBUG.log` in `$HOME/.local/state/dzgui/logs`

**Comment by aclist** [comment]
Closed due to inactivity
