### ISSUE TITLE
Requires jq >= 1.6

### ISSUE THREAD

**Issue by Piythos** [aclist/dztui#142]
im new to Linux and when i type that command and a GUI pops up and says "Requires jq >= 1.6". also im on mint

**Comment by aclist** [comment]
For Ubuntu-based distributions, the below should do the trick:

```
sudo apt-get update
sudo apt-get install jq
```

**Comment by Piythos** [comment]
> For Ubuntu-based distributions, invoking the below in a terminal should do the trick:
> 
> ```
> sudo apt-get update
> sudo apt-get install jq
> ```

thanks

**Comment by aclist** [comment]
Closing as resolved
