### ISSUE TITLE
Space inserted after name causing repeated kicks from server

### ISSUE THREAD

**Issue by OliveAlpaca** [aclist/dztui#145]
The launcher seems to be inserting a space after I input my custom name. This causes me to be instantly kicked from servers.
I deduced this from the following lines in the crash logs;

-name=Hannibal Lecter "

Essentially the space after the name but before the " seems to be the issue.

**Comment by aclist** [comment]
Thank you for the report. You marked this issue as complete. Does this mean you resolved the issue already?
