### ISSUE TITLE
Expand documentation

### ISSUE THREAD

**Issue by aclist** [aclist/dztui#15]
[DZGUI documentation](https://aclist.github.io/dzgui/dzgui.html)
DZTUI documentation: WIP

**Comment by SteveIDusa** [comment]
### @aclist

Its pretty late here, but noticed you had closed the issue and invited to discuss docs here.  Decided that I would read a bit tonight before heading to bed.  Looks pretty darn good so far, got down to usage, will pick it up tomorrow and continue from there.  Thank you for the invite.

**Comment by SteveIDusa** [comment]
### @aclist 
Finished reading the Docs page, only thing I found that felt to me like it was confusing or could be confusing was in the Usage Section.  I felt that it could benefit from a slight rewording to indicate that the user will need to sign into the Steam Workshop in the system web browser that opens besides as well being signed into the Steam Client.  I just felt as if I knew I was signed into the Steam Client I could potentially be confused as to why mods are not syncing when clicking the subscribe button in the browser.  

I suppose when they click the subscribe button in the browser it will prompt them, but for some I bet this will be confusing, perhaps this is just some autism or OCD speaking, but I felt I had better mention that my mind struggled at this section, and I am familiar with the process.

Overall, very good!!  Thank you again.

**Comment by aclist** [comment]
I think when you subscribe in the browser when Steam isn't open, it just schedules them, but I'm not entirely sure, haven't tried that yet. 

That seems like a good rewording to make. I agree that the mod subscription thing is the most sticky part of the process and feels awkward at times.

The fully automated mod installation using Valve's steamcmd is working well now on the DZTUI side, but I'm a bit reluctant to port it over to DZGUI because you have to input your sudo password and Steam credentials to log in and have the mods downloaded in the background, so I thought it might give some users pause as to where their credentials are going, since on DZGUI you can't explicitly see what's going on under the hood, given that the onscreen interface takes over.

For now, I am sort of keeping DZTUI as the "expert mode" and DZGUI as the user-friendly mode, but it would be cool to have feature parity on them. There are a couple of bugs we found over there that do apply to DZGUI, such as the rare case of Steam just refusing to load the game if 30+ mods with long titles are passed to it, so I plan to bring that change into DZGUI this week to prevent that rare problem.

There are a couple of other small QOL changes coming as well. I think it's looking stable now, but as always, I remain open to your suggestions. Anything that can be incorporated into the app is fair game IMO. I recently added functionality to add main menu options on the fly depending on what mode is selected, so you can have a set of advanced/debug options that arent listed under normal use. 

I think you mentioned listing the number of mods, but I'm still thinking about this, because we are running out of room in the table, and having to scroll a table horizontally always feels annoying.

**Comment by SteveIDusa** [comment]
### @aclist 

I know when I do it on my system, I know I am signed into the Steam Client, I then sign into the Workshop via the system web browser when I right-click the first mod link in the first browser window, then select open in new tab.  So I end up signed in on both, and as soon as I click on subscribe, it starts downloading in the Steam Client.  So no scheduling seems to take place, it is nearly instantaneous that the Steam Client starts a download.  The only delay that I have encountered was large mods or maps.

Also, got the new version today, which seems to be working perfectly.  Even checked the New Documents link and confirmed that it got to the right page.

If I think of anything I will be happy to let you know.  Thank you again for the great solution!

**Comment by aclist** [comment]
> Also, got the new version today, which seems to be working perfectly. Even checked the New Documents link and confirmed that it got to the right page.

Great!

> One Other thing, need a link to the dzgui version on the dztui page, at least I am having trouble finding it....

I was keeping it somewhat obscure because I didn't feel it was at a stable enough point for general consumption, and would only invite a barrage of support tickets. I feel like it's mostly in a good place now, so my roadmap for this week is:

- Toggle debug mode in-app (DZGUI)
- Port safer symlink method from DZTUI to DZGUI
- Port `dztuirc` config file format to DZTUI so that same config file can be used on both versions
- Create DZTUI documentation based on DZGUI format
- Create proper landing pages on each repository page

DZTUI has been in stealth mode too, but lots of changes under the hood over the last week.

DZGUI is located under a sub-branch of DZTUI, but perhaps it merits its own fork.
The DZGUI branch can be found here: https://github.com/aclist/dztui/tree/dzgui
I also included a screenshot and link to the documentation there.

> I hope you see lots of traffic

It would definitely be good to stress  test on more setups. It seems the biggest variable right now is the varied server configurations, which always present something new and unforeseen.

**Comment by SteveIDusa** [comment]
### @aclist 

Got it, OK, well I hope that I did not step to far over that boundary that I was not aware of.  My apologies now!  All the same, it appears to me ready for some usage by the community as it totally solved my use case and I am only a "casual" user of DayZ and Linux.  Which I suspect that with the way that Microsoft is pushing telemetry and data collection the Linux Community will see some growth.  And for those users that are trying to adjust from Windows (Where everything a casual user will do is in a Window) this tool is very welcome.  So I do hope it sees some deserved success.

**Comment by aclist** [comment]
Not at all, it is fine, we actually got it into a nice state thanks to your ongoing contributions and feedback. The reason I prepared the documentation was because I felt it was ready for general consumption at this point. 

Your wanting to share it with others I think is an indication of your current level of satisfaction that it is doing what it's supposed to, so I think that's a good sign of having ironed out bugs. 

By all means share it with the people you play with; the quality of an application lives and dies on its users. I can't test every permutation of server or config out there, so having more data points is the best way to improve it and make it better for other people.

I don't consider it feature complete, so I'm not ready quite yet to bask in the glory, but I appreciate your positive remarks and I am glad it helps you! One day I, too, will play DayZ. It takes up time to work on the tool, so not much room for playing the game besides loading up servers to see they work right. It's kind of like when you spend all your time tweaking your computer hardware and never get around to using it, right?

**Comment by aclist** [comment]
Those look nice. I can't do 3D, I'm not a good spatial thinker. I always have problems when 3D printing stuff. What is a good home printer to use these days?

Some small changes to the DZGUI backend this week, but nothing that should affect the end-user (hopefully).

**Comment by SteveIDusa** [comment]
### aclist

Not able to give you a brand or model, can only point you to our FAQ page on the site.  There are a few examples there of printers that are just large enough, as well as some guidance on how to come to a decision.  Which is all we are willing to provide.  Being that all of them have there pros and cons.  So you have to come to your own decision by your own research.

On top of that, the learning curve is such that it will not matter which we think is best, we would be putting a stamp of approval on something that is being controlled and adjusted by someone else.  Not a great scenario....

**Comment by aclist** [comment]
Alright, that makes sense. Thanks.

**Comment by SteveIDusa** [comment]
### @aclist

I went back and re-read troubleshooting, just to ensure that I remembered reading it previously, which I do.  When I read it, I do not have anything that jumps off of the page for me.  It appears to me to be minimal and concise.  I am afraid that my interactions with getting mods to download all seem to fit under those items listed and I did not experience any problems getting mods unless I made the mistake of removing a mod folder that I shouldn't have.  I did think that it might be beneficial to have a little more about the the amount of time that some mods take to download, but then I think, yeah but anyone that has any experience downloading mods or maps should be familiar with it already.....So when I think that, what is there seems quite adequate.

It is a brilliantly simple and effective tool and I am very happy with it!  Thank you again!
