### ISSUE TITLE
Cannot locate DayZ during install

### ISSUE THREAD

**Issue by mattrobineau** [aclist/dztui#153]
I am at the install step:

```
Specify the root, top-level entry point to Steam, not DayZ. E.g.,

/media/mydrive/Steam, not /media/mydrive/Steam/steamapps/common/DayZ
```

My steam install has two different install locations, the first is in `~/.steam/steam` and the other in `/mnt/games/SteamLibrary` (this is a second drive). The second location is where I installed DayZ. 

When I point to the drive where I have DayZ installed (`/mnt/games/SteamLibrary`), I get the following error:
```
usage: vdf2json [-h] [-i INPUT] [-o OUTPUT]
vdf2json: error: argument -i/--input: can't open '/mnt/games/SteamLibrary/steamapps/libraryfolders.vdf': [Errno 2] No such file or directory: '/mnt/games/SteamLibrary/steamapps/libraryfolders.vdf'
```

When I point the installer to the steam directory `~/.steam/steam`, I do not get the above error but the installer cannot find the game:
```DayZ not found or not installed at the Steam library given.```

 I assume its because its on the second drive.

If I copy `~/steam/steam/steamapps/libraryfolders.vdf` to `/mnt/games/SteamLibrary/steamapps/libraryfolders.vdf`, the error of a missing vdf disappears but the installer does not find the game.

My libaryfolders:
```
"libraryfolders"
{
	"0"
	{
		"path"		"/home/matt/.local/share/Steam"
		"label"		""
		"contentid"		"7123947908373435851"
		"totalsize"		"0"
		"update_clean_bytes_tally"		"2352785508"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"228980"		"175163215"
			"1265820"		"2123307416"
			"1493710"		"1217465964"
			"1628350"		"768561705"
			"2348590"		"1224814506"
			"2805730"		"1191908734"
		}
	}
	"1"
	{
		"path"		"/mnt/games/SteamLibrary"
		"label"		""
		"contentid"		"1196516618758508692"
		"totalsize"		"983334674432"
		"update_clean_bytes_tally"		"2333539841"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"248610"		"1134704679"
			"275850"		"20206172314"
			"975370"		"287340714"
			"1940340"		"4873868229"
			"2016590"		"10421750259"
		}
	}
}
```

After failing to install with the above vdf on the second drive, I tried modifying it on the second drive to only have the second entry (and changed the "1" to "0") but that didn't change anything.

DayZ install location:
```
> ls -la /mnt/games/SteamLibrary/steamapps/common/DayZ/
drwxr-xr-x    - matt 27 Sep 18:50 Addons
.rwxr-xr-x 112k matt 27 Sep 18:50 amd_ags_x64.dll
drwxr-xr-x    - matt 27 Sep 18:50 BattlEye
.rwxr-xr-x 7.5M matt 27 Sep 18:50 CrashReporter.exe
.rwxr-xr-x 1.7k matt 27 Sep 18:50 dayz.gproj
.rwxr-xr-x 1.3M matt 27 Sep 18:50 DayZ_BE.exe
.rwxr-xr-x  17M matt 27 Sep 18:50 DayZ_x64.exe
.rwxr-xr-x  19M matt 27 Sep 18:50 DayZDiag_x64.exe
.rwxr-xr-x 1.8M matt 27 Sep 18:50 DayZLauncher.exe
.rwxr-xr-x  11k matt 27 Sep 18:50 DayZLauncher.exe.config
.rwxr-xr-x 608k matt 27 Sep 18:50 DayZUninstaller.exe
drwxr-xr-x    - matt 27 Sep 18:50 DeluxeEdition
drwxr-xr-x    - matt 27 Sep 18:50 dta
drwxr-xr-x    - matt 27 Sep 18:50 EmptySteamDepot
.rwxr-xr-x  663 matt 27 Sep 18:50 installscript.vdf
drwxr-xr-x    - matt 27 Sep 18:50 Launcher
.rwxr-xr-x 299k matt 27 Sep 18:50 steam_api64.dll
.rwxr-xr-x    6 matt 27 Sep 18:50 steam_appid.txt
```

EDIT: [DZGUI_DEBUG.log](https://gist.github.com/mattrobineau/25db193f158b606e41fca2d283fd6cbc)

**Comment by mattrobineau** [comment]
I was reading through the closed issues and stopped [this reply](https://github.com/aclist/dztui/issues/72#issuecomment-1566204067) of yours where you mentioned the age old "Turn if off and back on again". 

Closing steam and restarting it after having just installed DayZ fixed the issue

**Comment by aclist** [comment]
Thanks for the message. It seems you found the answer, but essentially, if you have moved around the location of a game, Steam may not update this information within its files until the next restart. A summary of this is described at the knowledge base here: https://aclist.github.io/dzgui/kb.html#DZG-006

Forcibly moving around libraryfolders.vdf or editing its contents is not the trick here--it's best to let Steam manage this update by, if necessary, restarting Steam itself.
