### ISSUE TITLE
No Livonia map search

### ISSUE THREAD

**Issue by Dalailamer0684** [aclist/dztui#166]
Hi,
I am on DZGUI 5.6.0-beta.2.
OS Nobara 40 KDE Plasma.
In the Server Browser tab I cant search for only Livonia servers

**Comment by Dalailamer0684** [comment]
Dont know if I were blind. Founf it 2 mins ago

**Comment by aclist** [comment]
The internal name for Livonia is `enoch`. If a server lists its map as `livonia`, this is a mistake on the server administrator's part. If you filter for servers running the `enoch` map, you'll find them. (This name comes from Arma 3)
