### ISSUE TITLE
[BUG] Local mod list is malformed and triggers spawn_dialog

### ISSUE THREAD

**Issue by aclist** [aclist/dztui#168]
_Originally posted by @jiriks74 in https://github.com/aclist/dztui/issues/167#issuecomment-2505879818_

Also perform these steps:

- Navigate to `$HOME/.local/share/dzgui/helpers`
- Invoke `./funcs "List installed mods" > mymods`
- Save the below to `test.py`

```Python
import csv
import locale
import sys
import traceback

delimiter="␞"

def parse_mod_rows(file):
    sum = 0
    with open(file, "r") as infile:
        lines = [line.rstrip() for line in infile]
    hits = len(lines)
    reader = csv.reader(lines, delimiter=delimiter)
    try:
        rows = [[row[0], row[1], row[2], locale.atof(row[3], func=float), None] for row in reader if row]
    except (IndexError, ValueError):
        print(traceback.format_exc())
        return 1
    for row in rows:
        size = float(row[3])
        sum += size
    print([sum, hits])

if len(sys.argv) < 2:
    print("Supply a filename as argument")
    sys.exit(1)
parse_mod_rows(sys.argv[1])
```

- Invoke `python3 test.py mymods`
- If the output is clean, it should print the total mod size and number of mods. If the data is malformed, post the traceback

**Comment by jiriks74** [comment]
You're here at the right time! I've just started looking into the code a bit. I have some issues understanding `ui.py` but I've just started looking into `funcs`. I'll post you the output of what you posted in just a minute.

**Comment by jiriks74** [comment]
`funcs` reports some issues:

<details>
<summary><code>stderr</code> output of `funcs`</summary>

```bash
./funcs: line 357: printf: 99.587: invalid number
./funcs: line 357: printf: 32.837: invalid number
./funcs: line 357: printf: 302.4933: invalid number
./funcs: line 357: printf: 575.7433: invalid number
./funcs: line 357: printf: 104.6573: invalid number
./funcs: line 357: printf: 5.3448: invalid number
./funcs: line 357: printf: 3364.5519: invalid number
./funcs: line 357: printf: 12.7355: invalid number
./funcs: line 357: printf: 0.0323: invalid number
./funcs: line 357: printf: 1070.5245: invalid number
./funcs: line 357: printf: 111.3956: invalid number
./funcs: line 357: printf: 34.0909: invalid number
./funcs: line 357: printf: 132.6964: invalid number
./funcs: line 357: printf: 66.3448: invalid number
./funcs: line 357: printf: 2110.1339: invalid number
./funcs: line 357: printf: 1304.7667: invalid number
./funcs: line 357: printf: 142.8175: invalid number
./funcs: line 357: printf: 0.8292: invalid number
./funcs: line 357: printf: 1492.7159: invalid number
./funcs: line 357: printf: 8.4738: invalid number
./funcs: line 357: printf: 852.5831: invalid number
./funcs: line 357: printf: 0.0402: invalid number
./funcs: line 357: printf: 9.8644: invalid number
./funcs: line 357: printf: 88.712: invalid number
./funcs: line 357: printf: 11.6847: invalid number
./funcs: line 357: printf: 1111.0011: invalid number
./funcs: line 357: printf: 126.2198: invalid number
./funcs: line 357: printf: 0.7628: invalid number
./funcs: line 357: printf: 0.5128: invalid number
./funcs: line 357: printf: 70.0089: invalid number
./funcs: line 357: printf: 87.5245: invalid number
./funcs: line 357: printf: 48.9581: invalid number
./funcs: line 357: printf: 0.0362: invalid number
./funcs: line 357: printf: 204.5128: invalid number
./funcs: line 357: printf: 1910.9191: invalid number
./funcs: line 357: printf: 49.3917: invalid number
./funcs: line 357: printf: 465.9542: invalid number
./funcs: line 357: printf: 2.2042: invalid number
./funcs: line 357: printf: 304.9308: invalid number
./funcs: line 357: printf: 90.7823: invalid number
./funcs: line 357: printf: 9.1613: invalid number
./funcs: line 357: printf: 250.8605: invalid number
./funcs: line 357: printf: 129.5284: invalid number
./funcs: line 357: printf: 13.6261: invalid number
./funcs: line 357: printf: 68.8761: invalid number
```

</details>

**Comment by aclist** [comment]
There are only two possibilities that can trigger this:

1. funcs file returned with exit code 1 because there were no local mods, or with exit code 1 because something went wrong while dumping local mods (and we aren't catching and handling this error)
2. Internal method for parsing the mods list failed, and UI believes there are 0 mods, thus triggering a warning popup

**Comment by jiriks74** [comment]
`test.py` also has some issues but it crashes.

```python
Traceback (most recent call last):
  File "/home/jirka/.local/share/dzgui/helpers/test.py", line 15, in parse_mod_rows
    rows = [[row[0], row[1], row[2], locale.atof(row[3], func=float), None] for row in reader if row]
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/901c80rlps5q05bnjk1sj4zaz5k736nc-python3-3.12.7/lib/python3.12/locale.py", line 323, in atof
    return func(delocalize(string))
           ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '250,000'
```

**Comment by jiriks74** [comment]
With `LC_ALL=C` For both `funcs` and `test.py` the output is the following:

```
[16881.428, 45]
```

**Comment by jiriks74** [comment]
Ok, I'll test it right away!

**Comment by aclist** [comment]
Honestly, you are the best person to catch these bugs because of your locale settings, but yeah, locale check is usually something that gets forgotten, so that's my fault. I need to write more tests to take into account different locales.

**Comment by jiriks74** [comment]
Just tested using my package (I did this first so that I'd know if my update process works as intended) and everything seems fine!

![image](https://github.com/user-attachments/assets/e5590cfa-6f78-476d-92fd-3f391ad33fd8)

I can't check `Highlight stale mods` as I currently run only one server.

**Comment by aclist** [comment]
> Just tested using my package (I did this first so that I'd know if my update process works as intended) and everything seems fine!

Thanks for confirming!

> I can't check Highlight stale mods as I currently run only one server.

If you want to test it:

- Go to server browser, find a server with mods (right click > `Show server-side mods`)
- If the server shows you are missing some mods (no checkmark), use that server
- Right click and save to your servers
- Enable debug mode on the right panel
- Do a dry run connecting to this server so that mods get downloaded but game doesn't launch
- Go to your saved servers, right click, remove this server
- Go to mods list and highlight stale

Result: should show that some mods are no longer relevant.

You can ctrl-click to select single rows and shift-click to select ranges

**Comment by jiriks74** [comment]
Doing this RN

> If you want to test it:
> 
>     * Go to server browser, find a server with mods (right click > `Show server-side mods`)
> 
>     * If the server shows you are missing some mods (no checkmark), use that server
> 
>     * Right click and save to your servers
> 
>     * Enable debug mode on the right panel
> 
>     * Do a dry run connecting to this server so that mods get downloaded but game doesn't launch
> 
>     * Go to your saved servers, right click, remove this server
> 
>     * Go to mods list and highlight stale

I'll wait until the mods get downloaded and we'll see.

**Comment by aclist** [comment]
> I just can´t delete the server. I added another one, set it as a favorite but the server still won't get deleted.

Can you clarify this? Is this a UI bug? Not sure I'm understanding the steps taken.

> So everything works now!

Technically, there is one thing I'm looking into that seems to need fixing. Even when deleting mods, there's a chance that in the future, Steam will try to redownload a bunch of mods you had before if the workshop metadata doesn't get cleaned up accordingly. I'm prototyping a fix that will not simply delete the mods themselves, but also update the workshop metadata so that Steam won't try to grab them again. I keep having to download 50GB of mods, so I know this is not 100% where it needs to be. It's not something you would notice unless you are constantly deleting all of your mods (which I am, for testing purposes). Anyway, that fix is underway.

**Comment by jiriks74** [comment]
So `Highlight stale mods` works.

I manually selected some red mods and removed them.
The list refreshed but the `Highlight stale mods` button was still *turned on* but no mods were red. Had to click it twice (turned it off and on again) to get them red again.

Then I manually selected the rest and deleted them.

**Comment by jiriks74** [comment]
> Can you clarify this? Is this a UI bug? Not sure I'm understanding the steps taken.

`My saved servers` => `Right click` the only server in the list => `Remove from my servers` => `Main menu` => `My saved servers` => It's still there

<details>
<summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/1deec48f-29e6-4fa3-93a6-47f1543de31a)

![image](https://github.com/user-attachments/assets/141bc453-4f57-4844-ad90-1a645a74f62b)

![image](https://github.com/user-attachments/assets/97c62244-ea52-4e2e-b508-03c76194e54a)

![image](https://github.com/user-attachments/assets/c59f120a-ba5f-4387-8430-d83d4f07d621)

![image](https://github.com/user-attachments/assets/62eb1cc8-2db0-4f09-9bdb-57cdfae45992)

![image](https://github.com/user-attachments/assets/5f078dae-2ff4-4121-9e19-0ab9f2a56d6f)

</details>

**Comment by aclist** [comment]
Closing as resolved
