### ISSUE TITLE
Mod Checking Issue

### ISSUE THREAD

**Issue by escott173** [aclist/dztui#17]
After updateing to 2.2.1, when connecting to a server I have all of the mods for, the mod check appears to fail and does not pass the correct parameters to steam. Looks like an issues with collecting mod names via jq?

[xanthor@zork dztui-dzgui]$ ./dzgui.sh
[DZGUI] Setting architecture to 'desktop'
[DZGUI] Setting favorite server to 'nitrado.net Chuk's Dayz Server'
[DZGUI] Attempting connection to nitrado.net Chuk's Dayz Server
[DZGUI] Querying modlist on 95.156.238.217:
jq: error (at <stdin>:0): Cannot iterate over null (null)
[DZGUI] Passed mod check
[DZGUI] All OK. Launching DayZ

When I log into the server I get kicked saying I do not have the correct mods installed, however: I do!

**Comment by escott173** [comment]
On further inspection - loading the server from the server list works fine, but going from the menu to join your favorite server is where the error comes up.

**Comment by aclist** [comment]
Yes, it is a regression and the fix is ready, will update it later today (~2 hours). Sorry for the inconvenience.

**Comment by aclist** [comment]
The new version is live and should fix this issue. I also added a bit more error handling to check for incorrect results and gracefully fall back to the menu.

**Comment by escott173** [comment]
tested and it works! Thanks.
