### ISSUE TITLE
[BUG] Last saved server is not removed from list

### ISSUE THREAD

**Issue by aclist** [aclist/dztui#171]
`My saved servers` => `Right click` the only server in the list => `Remove from my servers` => `Main menu` => `My saved servers` => The server is still there

<details>
<summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/1deec48f-29e6-4fa3-93a6-47f1543de31a)

![image](https://github.com/user-attachments/assets/141bc453-4f57-4844-ad90-1a645a74f62b)

![image](https://github.com/user-attachments/assets/97c62244-ea52-4e2e-b508-03c76194e54a)

![image](https://github.com/user-attachments/assets/c59f120a-ba5f-4387-8430-d83d4f07d621)

![image](https://github.com/user-attachments/assets/62eb1cc8-2db0-4f09-9bdb-57cdfae45992)

![image](https://github.com/user-attachments/assets/5f078dae-2ff4-4121-9e19-0ab9f2a56d6f)

</details>

_Originally posted by @jiriks74 in https://github.com/aclist/dztui/issues/168#issuecomment-2506348800_

**Comment by aclist** [comment]
I can't reproduce this yet.

- Check your config file before and after the deletion action to visually confirm the change
- Check if you have multiple (old) entries for the same server in your config file (possible if using a legacy config file)
- Check if config file is read only

If the config file is clean, the table cache is not updating correctly.

**Comment by aclist** [comment]
@jiriks74 see above

**Comment by jiriks74** [comment]
> @jiriks74 see above

I did see it however I don't have the time to test it for you and, sorry. 

I'll try looking into it on Sunday.

**Comment by jiriks74** [comment]
> Check your config file before and after the deletion action to visually confirm the change

Did

```bash
$ diff dztuirc dztuirc.bac
```
got no output.

> Check if you have multiple (old) entries for the same server in your config file (possible if using a legacy config file)

The relevant part looks like this:

```bash
#Favorited server IP:PORT array
ip_list=(
	"109.230.239.204:2805:27021"
)

#Favorite server to fast-connect to (limit one)
fav_server="172.111.51.155:2302:2303"

#Favorite server label (human readable)
fav_label="Rearmed US3 | 5 Man Max"
```
> [!Note]
> I changed my fav server to something else just in case DZGUI would add it back to `My saved servers` list automatically.

> Check if config file is read only

```bash
$ test -w dztuirc
$ echo $?
0
```

**Comment by aclist** [comment]
Thanks for waiting. This is kind of a rare case, but allow me to explain:

Some game servers have multiple hosts on different IPs. In general, these all point to the same game server, but they have discrete IPs. There might be various reasons for this, or the IP was rotated. 

In any case, the game server IPs that get indexed may not be the canonical IP of the destination server. In your case, the last server you had in your favorites list (server with IP XXX) was resolving to a game server (server with IP YYY). Same server, two different IPs.

When the server was saved into your config file, it was saved with the IP-as-shown, rather than the IP-as-resolved. You probalby saved this server awhile ago.

When trying to remove the server from your config file, it was searching for a record with the the IP-as-resolved, but your config file had the old IP-as-shown, so it could never be found in the configs, even though the old IP was still resolving to a valid server and showing up in the list.

To address this, I've added additional logic to resolve IPs in the server browser and save the address of record, rather than the superficial IP that was shown in the index. This is merely an additional sanity check that is probably redundant in most cases, but is being applied to all Add/Remove Server contexts just to make sure the IPs we are looking for are the same as the ones that go into the config files.

> [!NOTE]  
Going forward, this should not happen again, but you'll also need to manually intervene in your config file and remove that line, then re-add the server so that it gets saved with the correct destination IP.
