### ISSUE TITLE
[BUG] Only showing up to 10 servers on list and scaning 10 servers on list

### ISSUE THREAD

**Issue by lescuer97** [aclist/dztui#22]
**Info**
DZGUI version: 2.4.1
Mode: normal
Server ID:
Linux distribution: popos

**Bug description**
it only shows up until 10 servers  even if you have more than 10 servers saves.
 this affect pinging servers and listing for deletion

**To Reproduce**
1. Go to add more than 10 servers to the tool
2. Click on delete server and delete one server
3. go again to the server list and see that there is 10 severs again and one replacing the one that was deleted
Example: 
kriptic going to be deleted: 

![deleted kriptic](https://user-images.githubusercontent.com/47948594/183961471-993ea6d7-9d60-4346-b459-42eeb6fde46a.png)

After deleting kripting and not adding any more servers:

![after deleting kriptic](https://user-images.githubusercontent.com/47948594/183961553-b6edfd02-13df-4740-8dce-280ff72a5b35.png)

**Expected behavior**
should show the whole list of servers

**Comment by aclist** [comment]
Thanks, this is fixed on Testing. Can you please have a look before I push it to Stable?

1. Select `Toggle debug mode` from main menu
2. Select `Debug options` at bottom of list
3. Select `Toggle branch`
4. App will download Testing branch
5. Confirm that Mode is `debug` in the top header
6. Try server list/delete server functionality with >10 servers
7. When finished, repeat steps 2-3 above to toggle back to Stable branch

The API was returning results >10 behind a pointer to a paginated list, so the new logic loops through all available pages until it gets every result and stores them in an array.

**Comment by lescuer97** [comment]
I'm seeing the list now with more than 10 lines, but I can't start the game it gives me this output: 
![Screenshot from 2022-08-11 19-39-01](https://user-images.githubusercontent.com/47948594/184198761-af723fe0-88d2-433b-ab0c-5db182d68bcf.png)
I tried with debug mode and no debug mode but in test branch

**Comment by aclist** [comment]
I didn't have much time to test it end-to-end with servers yesterday after pushing the fix, but I see the problem. The fix is live on `2.4.2-rc.2`. I also reworded the error message to be more generic and not about favorite servers only.

**Comment by aclist** [comment]
Can you confirm that there are no further problems?

**Comment by aclist** [comment]
This is now live on Stable (`2.5.0`).
