### ISSUE TITLE
Cant Load mods

### ISSUE THREAD

**Issue by joelawm** [aclist/dztui#25]
**Info**
DZGUI version: 2.4.1
Mode (normal/debug): normal
Server ID: 15028824
Linux distribution: Pop OS

**Bug description**
Fails to load mod it only replaces all mods with @_w

From Options.log
steam -applaunch 221100 -connect=193.25.252.43:2302 -nolauncher -nosplash -skipintro "-mod=@_w;@_w;@_w;@HA;@_w;@zA;@sw;@_A;@_w;@KA;@_w;@_w;@_w;@_w;@_w;@_w;@_w;@Ug;@_w;@kA;@_w;@_w;@ig;@_w;@_w;@_w;@BA"

**To Reproduce**
1. Launch Server List
2. Double click the server to join.
3. Says failed to load mods after connecting for a few seconds.

**Expected behavior**
Should just join the server.

log
Version: 2.4.1
Branch: stable
Whitelist: 8039514,15028824
Path: /mnt/67ec537f-d8ff-4bfe-a8df-ec24c9be581f/SteamLibrary
Linux: Linux 5.18.10-76051810-generic x86_64

Mods:
Advanced Weapon Scopes	@jg
Airdrop-Upgraded	@dg
BadgerBuildings	@wg
Banking	@JQ
BaseBuildingPlus	@4g
Base Fortifications	@Sw
Base Furniture Mods 2.0	@Fg
Better Inspect	@qg
betterscopes	@dA
Breachingcharge	@BQ
BuildAnywhere_v3	@mA
BuilderItems	@gw
CF	@BA
CheckIdentity	@hA
Cheytac M200 from ArmA 2 Port	@uQ
CJ187_Drinks_Food	@Ew
Cl0ud's Military Gear	@4Q
Classic Names & Descriptions - No $UNT$	@fw
Close/Open Anywhere	@EQ
COCAs_NoVehicleDamageMOD	@]Q
Code Lock	@6g
Community-Online-Tools	@kA
CPBWeapons	@ww
[CrSk] BMW 525i E34	@uA
DayZ-Expansion-Licensed	@ig
DayZ-Expansion	@tg
DayZ Humanity	@8Q
Dayz Navigation	@yQ
DayZPlus Guns	@AA
Dingo_Truck	@Tg
DisableGardenPlots	@]w
Ear-Plugs	@pA
FlipTransport	@tw
Forever_Lights_and_Campfires	@zw
GAZ_Tigr_FIXED	@5w
Gold Nuggets	@mg
GoreZ	@xQ
GraveCross	@lg
Infected Wolf	@yg
InventoryPlus	@mQ
ItemCollisionNerf	@ew
MAG Server Mod	@vQ
Mass'sManyItemOverhaul	@vg
MedicalAttention	@IA
MoPlanks	@sg
MoreFood	@aw
MoreGuns	@1g
Mortys Weapons	@_w
MosinScope	@zg
MuchCarKey	@aA
MuchStuffPack	@KA
MunghardsItempack	@sA
NatureOverhaul	@iA
New Trader Menu	@qQ
NoMuffle	@]g
Notes	@WQ
NoVehicleDamage	@6A
OP_BaseItems	@yA
PartyMe	@zA
[PMEX] BackPack Mod	@gQ
PVEZ	@9g
PvZmoD_CustomisableZombies	@sw
Queue Connect Fix	@cg
[Remastered] Arma Weapon Pack	@Cw
Saline Bag+	@YA
SchanaModGlobalChat	@nA
SchanaModParty	@VQ
Server_Information_Panel	@hg
Simple Base	@Jg
SIX-DayZ-Auto-Run	@NQ
SkinInfected	@QQ
SQUAD MSF-C	@TQ
Supressor Hybrid	@Ng
The Wall Fallen But Rearmed Sunny DayZ After All	@XA
The Wall Fallen But Rearmed Sunny DayZ After End	@Ww
The Wall Paradise Hideout Fallen But Russian Zone Rearmed	@NA
Trader	@rA
Treasure	@HA
TweakRaidTools	@ng
Unknown Ghillie Mod	@_A
Unlimited Stamina	@PQ
VanillaPlusPlusMap	@9A
VPPAdminTools	@VA
VPPNotifications	@Ug
WeaponReduxPack	@8w
X2Taser	@3Q
Zeroy-FishingZ	@2A
ZomBerry Admin Tools	@8A
zSpawnSelection	@]A

**Comment by aclist** [comment]
Hi, this is fixed on the Testing branch and will get merged into the Stable branch next week. It's an issue affecting servers with large numbers of mods.

To switch to the testing branch:

1. Select Toggle debug mode from main menu
2. Select Debug options at bottom of list
3. Select Toggle branch
4. App will download Testing branch
5. Return to normal mode by selecting Toggle debug mode again

These changes are essentially ready to get merged into mainline, but please test and confirm.

**Comment by aclist** [comment]
This is now live on Stable (`2.5.0`).
