### ISSUE TITLE
[BUG] Malformed game path

### ISSUE THREAD

**Issue by graves501** [aclist/dztui#26]
**Info**
DZGUI version: 2.5.0
Mode (normal/debug): normal
Server ID: not needed for this bug
Linux distribution: Manjaro

**Bug description**
After first time setup it's not possible to launch `dzgui` anymore. The `steampath` variable is set in the configuration file, in my case: `steam_path="/home/user/.local/share/Steam/steamapps/common/DayZ"`. Something weird might happen in the line `[[ ! -d $game_dir ]] && (err "Malformed game path")`.

**To Reproduce**
1. Run first-time setup
2. Fill in the values
3. Close the application
4. Restart the application. The application shows [Error] Malformed game path

**Expected behavior**
`dzgui` should launch with the created configuration after first-time setup.

**Comment by aclist** [comment]
It sounds like you have a Steam installation at `home/user/.local/share/Steam/` (it found this during the first-time setup), but when it tried to append `steamapps/common/DayZ` to it, this didn't exist.

Do you have multiple Steam paths? (Installed somewhere else) 

What is the result of this command?

```

find / -type d \( -path "/proc" -o -path "*/timeshift" -o -path "/tmp" -o -path "/usr" -o -path "/boot" -o -path "/proc" -o -path "/root" -o -path "/run" -o -path "/sys" -o -path "/etc" -o -path "/var" -o -path "/run" -o -path "/lost+found" \) -prune -o -regex ".*/steamapps/common/DayZ$" -print
```

I can change the first-time setup to keep looking for more possible Steam paths if, after finding the first one, it doesn't contain DayZ.

**Comment by graves501** [comment]
> Out of curiosity, do you normally re-run first time setup when a new version is released?

Well, it was my first time trying out the GUI version of `dztui`, so no I don't think I would re-run the first time setup if not necessary. 

Version `2.5.1` seems to fix the aforementioned problem. Thank you :smile:

**Comment by aclist** [comment]
OK, I was mainly asking because you said "it's not possible to launch anymore," so I thought you were using it already!

Sorry for the problems on your first-time experience, and glad it's working. Is DZTUI still working okay for you, by the way? I haven't touched it in a little while, but it should be stable for its given featureset.

**Comment by graves501** [comment]
> Is DZTUI still working okay for you, by the way?

I haven't really used `dztui` for launching any servers in a while since I just used your command outputs as aliases. I sometimes use it for listing the servers and their player counts. Which works perfectly fine by the way!

But if I have time in the upcoming future I can test it more thoroughly... it's been a few months!

Thanks for your contribution to Linux gaming! Very much appreciated!
