### ISSUE TITLE
ping: : Name or service not known

### ISSUE THREAD

**Issue by sakulzz** [aclist/dztui#3]
Hello wanted to try dztui, when i try starting it this comes up.

ping: : Name or service not known

what did i do wrong?

**Comment by aclist** [comment]
Please submit a paste of your current file, omitting any sensitive data (API key, username, etc.).

**Comment by sakulzz** [comment]
I alraedy got it thanks.

**Comment by aclist** [comment]
OK, thank you. There is a new version of the script available. Please report if you have further issues.
