### ISSUE TITLE
[BUG] Steam Deck not finding game path. External drive compatibility?

### ISSUE THREAD

**Issue by ryanrambharose** [aclist/dztui#32]
**Info**
DZGUI version: Newest
Mode (normal/debug): Normal
Server ID: Not Applicable
Linux distribution: Steam OS

**Bug description**
I have my game on an external drive in this case the Steam Deck SD card. I have tried manually specifying the path. Maybe due to a drive permission error?

**To Reproduce**
1. Edit config and use the SD card game path
2. Malformed pop-up

**Expected behavior**
Add game path should be able to run the launcher

**Comment by aclist** [comment]
It could be ownership; we could run some tests. But I assume the default user can read the contents of that card.

I'm wondering what the path looks like, though. Can you post the path (redacting any sensitive information)? The path must include `steamapps/common/DayZ` somewhere under it.

The path should be the top level path before entering the steamapps directory itself. E.g., if `steamapps` resides below `/my/drive/here`, the path to supply should be `/my/drive/here` alone.

Is the path enclosed with quotes in the config file?

Does the path contain spaces or special characters?

**Comment by ryanrambharose** [comment]
Here is the path: /run/media/mmcblk0p1/steamapps/common/DayZ/
It is enclosed in quotes in the config
No special characters it seem

**Comment by aclist** [comment]
The path you need to supply is `/run/media/mmcblk0p1`, nothing else.

**Comment by ryanrambharose** [comment]
That worked thank you

**Comment by aclist** [comment]
Thanks for confirming. Be aware of some design limitations: the SteamOS overlay in gaming mode will have difficulty entering text into certain fields, so you'll have the best experience in desktop mode.

**Comment by ryanrambharose** [comment]
I noticed that. I don't think the Steam Deck is at full performance in desktop mode. So, adding servers in desktop then playing in Game Mode seems like the solution at the moment.

**Comment by aclist** [comment]
Right, I don't think gamescope is enabled in desktop mode. There is actually a full server browser on the testing branch that facilitates searching for and connecting to any public server (instead of having to add servers and switch), but I think you'd be limited to browsing (versus searching by keyword) if using game mode.

I need to analyze this text entry issue further and escalate the problem to Valve, or considering using some alternative GUI scheme.

**Comment by ryanrambharose** [comment]
Is there a reason why with the official launcher my mods can be downloaded but are corrupted?

**Comment by aclist** [comment]
As far as I know, it is simply unsupported. This problem might be exacerbated if you have an RTX card. I don't know much else about the official launcher, as it's closed source.
