### ISSUE TITLE
[BUG] starting dzgui from steam stopped working after uppdate

### ISSUE THREAD

**Issue by BoLin4** [aclist/dztui#33]
**Info**
DZGUI version: 2.6.1
Mode (normal/debug):
Server ID:
Linux distribution: steam deck / SteamOS

**Bug description**
When i try to start from Steam I just get a small popup window(named: dzgui), with a warning sign ( ! ), saying only: requires jg >=1.6. 
Can only chose Exit from there.
Can still start from the terminal

**To Reproduce**
1. Go to Steam
2. Click on dzgui
3. Warnings box pops up

**Expected behavior**
The game to start like normal

**Comment by aclist** [comment]
I'm not able to reproduce this behavior yet. No underlying code was changed in version 2.6.1, just a newline that was removed.

Have you changed the underlying filesystem and packages on Steam Deck? What is the output of `command -v jq` in a terminal?

Is this on desktop mode or game mode?

**Comment by BoLin4** [comment]
I haven't done anything really, just tried starting it, got the update, then this. It happens in both desktop and gaming mode.(Not when going through the terminal with ./dzgui.sh though)
I will get back to you with the terminal input you gave me, I don't have the deck with me right now.
________________________________

**Comment by BoLin4** [comment]
problem solved itself, before putting in the line. thanks for the quick response though

**Comment by aclist** [comment]
OK, thanks for the update. Submit another report if you have problems.
