### ISSUE TITLE
[BUG] When quick launching a favourite server that is modded, the mods don't load

### ISSUE THREAD

**Issue by bongjutsu** [aclist/dztui#37]
**Info**
DZGUI version: 2.6.2, also happened in 2.6.1
Mode (normal/debug): Normal
Server ID: 16716438
Linux distribution: Arch Linux

**Bug description**
When setting a favourite server in dztuirc, then attempting to quicklaunch that server, the script doesn't properly append mods to the launch path.

When running in debug mode, this is the output of the dry run check:

[DEBUG] This is a dry run. These options would have been used to launch the game:

steam -applaunch 221100 -connect=***.***.***.***:**** -nolauncher -nosplash -skipintro "-mod="
Note: censored IP address for reasons

**To Reproduce**
1. Set favourite server id in dztuirc
2. Launch dztui
3. Quick connect to favourite server
4. DayZ launches, but without mods

**Expected behavior**
When launching the server "manually" through the script, it appends the mods just fine. It's only when quick connecting to favourite that it fails.

**Comment by aclist** [comment]
Sorry, wasn't aware there was a regression in there for a few versions. Pushed a hotfix that should fix it. Please check and confirm.

**Comment by bongjutsu** [comment]
Just gave it a test, seems to be fixed now
