### ISSUE TITLE
[BUG] Give a title to the report

### ISSUE THREAD

**Issue by jiriks74** [aclist/dztui#41]
**Info**
DZGUI version: latest
Mode (normal/debug): Normal
Linux distribution: KDE Neon (Ubuntu based)

**Bug description**
Python is not discovered as `python` is not symlinked to `python3`. Maybe use `python3` instead of `python`? To my knowledge all distributions that have `python3` have a binary named `python3`. I might be wrong though.

**Expected behavior**
Python 3 bring discovered

**Comment by aclist** [comment]
Yes, good observation. Hotfix pushed to Stable and Testing.
