### ISSUE TITLE
Doesnt Display full server list?

### ISSUE THREAD

**Issue by TwinDracos** [aclist/dztui#42]
**Info**
DZGUI version: 3.3.0-rc.1
Mode (normal/debug): Normal
Server ID: 2148824
Linux distribution:

**Bug description**

when searching for the server "TruckerJGaming Dayz" i get no matches, but this is in fact an active server. I've actually have noticed it with several game servers. its almost as if you only get half of the community games that are listed. 

**Steps to reproduce the behavior:**
1. Go to 'ServerBrowser' 
2. Click on ' keyword search' click ok
3. Type in 'TruckerjGaming'

**Expected behavior**

**Comment by TwinDracos** [comment]
i believe i may have figured it out. i needed to also toggle, empty. full, Low population.

**Comment by aclist** [comment]
That's correct. Low pop, empty, and full servers are excluded in the default settings because they may be undesirable to play on (and in the case of full, impossible). Of course, there are lots of smaller servers with a low population, so perhaps that option could be ticked by default.

**Comment by aclist** [comment]
I updated the Testing branch to have the low pop server option ticked by default. This change will be merged into the Stable branch soon.
