### ISSUE TITLE
[BUG] When trying to join a server it says Playerwaitauthlogin error

### ISSUE THREAD

**Issue by MAVR0W** [aclist/dztui#45]
I need some help trying to join a server I keep getting this error as well.

**Comment by aclist** [comment]
This error is caused due to servers implementing aggressive policies against high ping. It's not related to the application and we have no control over it. Try to pick servers that are geographically proximate to you for a better ping.

**Comment by aclist** [comment]
I looked into this some more, seems you need to install the Proton Battleye Runtime via the Tools section of your Steam library or you will be kicked from servers.
