### ISSUE TITLE
Not exactly a issue, but how do I uninstall?

### ISSUE THREAD

**Issue by MAVR0W** [aclist/dztui#46]
I think I found the issue with my machine, I need a clean install of this program and wondering how can I uninstall DayzGUI to reset my paths?

**Comment by aclist** [comment]
Remove:

- $HOME/.local/share/dzgui
- $HOME/.config/dztui
- $HOME/.local/share/applications/dzgui.desktop (if applicable)

I'll think about adding an uninstall script in the future.
