### ISSUE TITLE
[BUG] malformed api key

### ISSUE THREAD

**Issue by GKourp** [aclist/dztui#47]
**Info**
DZGUI version:3.3.0-rc.2
Mode (normal/debug): debug
Server ID:16171400
Linux distribution:

**Bug description**
upon launching dayzgui i am presenting with a pop up saying malformed api key, is there anyway to change the api key the app is using?

**Steps to reproduce the behavior:**
launch dayzgui and the pop up occurs

**Expected behavior**
expected the app to open normally, first time launching it

**Comment by aclist** [comment]
Did you supply the asked-for API key when performing first-time install? There are three values you had to supply. Currently we validate the Steam API key to verify that it is correct, but we don't explicitly validate the BM API key (this is planned) and trust the user to enter it correctly.

It's possible you entered a line break or extra character.

You can check the status of your keys in `$HOME/.config/dztui/dztuirc`.

`api_key` = BM API key
`steam_api` = Steam API key

**Comment by GKourp** [comment]
yes i did supply the key it requested, i followed the readme pretty close besides "Since this key is for a personal use application and does not actually call back anywhere, set a generic local identifier here like "127.0.0.1"." that part, I named it something else since I didn't think the name mattered. I also cannot find the directory you listed, is there an easy way to uninstall? Im very new to linux btw.

**Comment by aclist** [comment]
Are you on Steam Deck or desktop?

`$HOME` is an environment variable that maps to `/home/<your username/`. If you get a look at your config file, it should hold the answer as to what is happening--likely a malformed value.

You can test if the key is working in your browser by pointing it to a URL like this and supplying your key and Steam ID (found on your profile link): 

`https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=<APIKEY>&steamid=<STEAMID>&format=json`

That should return a list of games you own.

Uninstall instructions are in this ticket: https://github.com/aclist/dztui/issues/46

**Comment by GKourp** [comment]
I am on the steam deck. So I feel dumb but I follow the path and I just don't see api_key or steam_api. The browser opens after it tells me malformed api key if that is any help.

**Comment by aclist** [comment]
Sorry for the slow response due the year-end. I will be more active on here starting tomorrow. 

If I understand you correctly, there is no `dztuirc` file under `$HOME/.config/dztui`? `api_key` and `steam_api` are parameters inside of that text file.

What is the result of this command?

`find $HOME/.config/dztui/dztuirc`

**Comment by GKourp** [comment]
Sorry for the late response. I opened a file called dzgui.sh and it has a lot of lines of text, is this the file I should have been looking for? This is making me feel very dumb LOL.

**Comment by aclist** [comment]
No, you are looking for the file `/home/deck/.config/dztui/dztuirc`.

You can open Dolphin (the KDE file navigator) and go to:

home -> deck -> .config (this folder might be hidden) -> dztui -> find a file named dztuirc

**Comment by GKourp** [comment]
Awesome! Found the error in my token, it opens the launcher flawlessly now, but now when I go join a server it says, "This is a dry run.
These options would have been used to launch the game:", and what look to be launch parameters.

**Comment by aclist** [comment]
You must disable debug mode. Not sure how you managed to turn on debug mode during your first run unless you modified the config file.

Advanced Options -> Toggle debug mode

The header in the main menu should read "Mode: normal" when normal mode is on.

**Comment by GKourp** [comment]
Not sure myself, I must have done that tinkering around. I've managed to fix my errors with your endless patience, thank you.

**Comment by aclist** [comment]
I'm a bit curious as to how debug mode could get enabled on an initial installation, but I don't think it's possible from a design perspective. I'll try to reproduce this issue to see if it is indeed a bug.

I am glad you got it fixed. May I ask which of the two API keys was incorrect, and what you erroneously inserted? Did you add an extra line break? I'd like to know if I can defensively design around this to further prevent user error.

**Comment by GKourp** [comment]
I definitely put it in debug myself. As per the key, I entered a completely different value and not the token, I must have gotten confused while reading the instructions.

**Comment by aclist** [comment]
I'll fix this today by validating the information so that the user is prompted to re-enter it if they did it wrong. We do this for the Steam API already, but it was on my to-do list to add it for BM.

**Comment by aclist** [comment]
OK, this change is now live. If you enter the wrong API key on initial setup, it will check and warn you to enter it again.
