### ISSUE TITLE
[Bug] 2 issues  on the flatpak/regular implementation (I can't reopen the issue)

### ISSUE THREAD

**Issue by Zukureneno** [aclist/dztui#53]
Just to confirm that I tried the toggle on PikaOS.

1 error I found was that when user toggles to flatpak it reverts back to steam when dzgui closes. Besides that the toggle works and I was able to join my favorite server without issues on either version.
+ mod detection crosswork so I was able to launch without needing to re-download anything.

![Screenshot from 2023-01-19 15-45-48](https://user-images.githubusercontent.com/60487234/213472681-dae421e9-9b5d-4a6c-b426-30e5a0192053.png)
![Screenshot from 2023-01-19 15-47-04](https://user-images.githubusercontent.com/60487234/213473388-97f4f319-7b63-4f4a-970b-4cdea6fbe91b.png)

PS: Make sure to not have regular steam open or it will bug out when trying to download the mods XD (if you launch for flatpak)

_Originally posted by @Zukureneno in https://github.com/aclist/dztui/issues/52#issuecomment-1397122605_

**Comment by aclist** [comment]
That's a valid point, I guess it should be stored in the config file as a preference (I was avoiding doing this extra step).  I will work on that, please give me some time.

I guess not having both versions of Steam open is the user's responsibility. We could check and warn for this, but it seems like a rare case.

**Comment by aclist** [comment]
Follow-up question: does Flatpak steam still use the default Steam config path? (For example, `$HOME/.local/share/Steam` or `$HOME/.steam` for debian variants).

**Comment by Zukureneno** [comment]
> That's a valid point, I guess it should be stored in the config file as a preference (I was avoiding doing this extra step). I will work on that, please give me some time.
> 
> I guess not having both versions of Steam open is the user's responsibility. We could check and warn for this, but it seems like a rare case.

np take all your time. its already amazing that the modloader works natively .

Only thing I found is that even if i had only flatpak open and selected flatpak as soon as i joined a server that required a new mod it tries to open regular steam to download said mods and it locks up.
as for the config to be honest I'm not sure. I think it keeps all of it inside .var including configs and proton (is located on its .var folder) /home/USER/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common

![image](https://user-images.githubusercontent.com/60487234/213489817-b56457f7-9980-4c9a-a74b-51197a10fbad.png)

![image](https://user-images.githubusercontent.com/60487234/213490057-2ea8e5f9-dd27-4742-8ff0-415caf93b515.png)

I hope this info helps

**Comment by aclist** [comment]
Check `$HOME/.local/share/Steam` and see if it is symlinked to `.var/app/com.valvesoftare.Steam`, as it seems to be.

**Comment by aclist** [comment]
I'm not looking to find specific config files in there per se, it's just that we look for and save the path to Steam in order to determine where mods are being downloaded to and where they are going, etc. 

This might interfere with the initial setup process. Take a look at your config file `$HOME/.config/dztui/dztuirc`) and see what it has for the `default_steam_path` key. That's detected when setting up the app for the first time.

If this is not aligned, it could be the cause of the mod download problems. So to fully extend this and add Flatpak support at the level of more than just "what program do we use to launch this," we need to have a full setup routine that takes into account these different scenarios and reliably sets the path.

**Comment by aclist** [comment]
I also just pushed an update that should retain the preferred client setting and save it to the user's config file after it is chosen.

**Comment by Zukureneno** [comment]
> I'm not looking to find specific config files in there per se, it's just that we look for and save the path to Steam in order to determine where mods are being downloaded to and where they are going, etc.
> 
> This might interfere with the initial setup process. Take a look at your config file (`$HOME/.config/dztui/dztuirc`) and see what it has for the `default_steam_path` key. That's detected when setting up the app for the first time.
> 
> If this is not aligned, it could be the cause of the mod download problems. So to fully extend this and add Flatpak support at the level of more than just "what program do we use to launch this," we need to have a full setup routine that takes into account these different scenarios and reliably sets the path.

#Path to DayZ installation
steam_path="/mnt/SSD_Crucial/SteamLibrary"

#Path to default Steam client
default_steam_path=""

it never changes; I just tried to close it and open it; and open it after toggle .

**Comment by aclist** [comment]
`default_steam_path` is just a newer parameter that was added a few versions ago that is used to track where Steam itself is installed (matters for auto-installing mods), and is separate from `steam_path`, which is where DayZ is installed (can be on external drives). If it's empty, you've just been carrying over an older config file and didn't do first-time setup. It doesn't matter.

The parameter that will change when toggling is called `preferred_client` and is at the bottom of the file if you fetch the latest version.

I'm just asking about the default steam path in order to plan what to do here. It should only affect users who enable automod installation. Basically, when they first install the app, they would have to explicitly select the path to the Flatpak installation if that's the canonical version of Steam they want to use when auto-downloading mods (autodownloading puts mods in Steam's base directory, rather than the game drive). I don't think this is a problem per se, just something that should be mentioned in the documentation. Newer versions of DZGUI give the user a file picker dialog to set the default Steam path if they aren't satisfied with the one we auto-detected.

**Comment by aclist** [comment]
> But big issue is when having both installed and flatpak open it will always default to open regular steam to download mods(while having flatpak selected on the advance options).

OK, found the cause of this. `xdg-open` will just map to native Steam or Flatpak steam, whatever is available. It's not a command exclusive to Flatpak. So if you have both version installed and you want to explicitly use Flatpak steam, we should be using the long form of the command.

Does this invocation work?

`flatpak run com.valvesoftware.Steam steam://open/console`

**Comment by Zukureneno** [comment]
> 

Yes it worked!

**Comment by Zukureneno** [comment]
I just deleted the config and it did this:
#Path to default Steam client
default_steam_path="/home/zuku/.local/share/Steam"

but when I toggle it gave me this:
![image](https://user-images.githubusercontent.com/60487234/213505090-8b6e02ad-e818-445b-8952-1b0337461545.png)

**Comment by aclist** [comment]
Use the testing branch, please, as it contains the latest fixes we are talking about here.

**Comment by aclist** [comment]
> but when I toggle it gave me this:

This is a separate bug, I am fixing it now.

**Comment by Zukureneno** [comment]
> Use the testing branch, please, as it contains the latest fixes we are talking about here.
> 
> Test downloading mods when both versions of Steam are open => should be fixed now

at the moment I can't move forward with flatpak since it gives me the Steam must be running to use this feature bug . Regular its working

**Comment by aclist** [comment]
So:

1. Flatpak Steam is running in the background
2. You toggle native/Flatpak in the advanced options menu
3. You get this message?

Make sure you are on version=3.3.0-rc.5, as there was a bug in the way the advanced options list was behaving.

**Comment by Zukureneno** [comment]
> So:
> 
> 1. Flatpak Steam is running in the background
> 2. You toggle native/Flatpak in the advanced options menu
> 3. You get this message?
> 
> Make sure you are on version=3.3.0-rc.5, as there was a bug in the way the advanced options list was behaving.

ok the msg is not there with latest rc.5 (it was with rc.4; I was testing at the same time as you pushed the update lol)

**Comment by Zukureneno** [comment]
> So:
> 
> 1. Flatpak Steam is running in the background
> 2. You toggle native/Flatpak in the advanced options menu
> 3. You get this message?
> 
> Make sure you are on version=3.3.0-rc.5, as there was a bug in the way the advanced options list was behaving.

zuku@zuku-PikaOS ~ [SIGTERM]> ./dzgui.sh
[DZGUI] Checking response time of servers
/home/zuku/dzgui.sh: line 386: flatpak run com.valvesoftware.Steam: command not found
Got this when trying to download mods (flatpak steam open alone+flatpak is toggled)

#Path to default Steam client
default_steam_path="/home/zuku/.local/share/Steam"

#Preferred Steam launch command (for Flatpak support)
preferred_client="flatpak run com.valvesoftware.Steam"

**Comment by aclist** [comment]
> ok the msg is not there with latest rc.5 (it was with rc.4; I was testing at the same time as you pushed the update lol)

I'm still curious about this message, because it's used by another process and should work correctly if Steam is up. (Basically, you were selecting menu option 5 but it was giving you menu option 4). 

What do you get if running this?

`xdotool search --onlyvisible --name "Steam"`

> one interesting behavior I found was (If I start flatpak first then steam) and choose steam as default it will work to download mods.
However If I open steam first then flatpak second it will not work and lockup.

(this happens cause Steam goes offline on the first instance and goes online on the second)

I'm not sure about this, sounds like it might be out of our control and needs time to synchronize your login state. I know the behavior you are talking about. 

> Toggle options has to match whichever Steam versions is currently Online and has connection.

I don't think there is a way of programmatically determining this through a third-party program. This is a big ask. It should be the responsibility of the user to properly close out of other instances before doing this sort of thing.

Out of curiosity, if you have it installed, try running `xprop` and then interactively selecting the Flatpak Steam window by clicking the mouse cursor on it. It should print debug info to the terminal and contain a line like `WM_CLASS(STRING)= "<some name>"`

<some name> should mention Steam and/or Flatpak somewhere. If Flatpak Steam has a uniquely identifiable name like "Steam: Flatpak", then we can target it. But if it's just called "Steam", we may not be able to.

**Comment by aclist** [comment]
> zuku@zuku-PikaOS ~ [SIGTERM]> ./dzgui.sh
> [DZGUI] Checking response time of servers
> /home/zuku/dzgui.sh: line 386: flatpak run com.valvesoftware.Steam: command not found
> Got this when trying to download mods (flatpak steam open alone+flatpak is toggled)

This is fixed now, was related to word splitting due to the command consisting of multiple arguments. It was being treated as a single command.

**Comment by aclist** [comment]
I took a look and it doesn't seem like Steam Flatpak has any unique identifiers to distinguish it from normal Steam.

**Comment by Zukureneno** [comment]
> > ok the msg is not there with latest rc.5 (it was with rc.4; I was testing at the same time as you pushed the update lol)
> 
> I'm still curious about this message, because it's used by another process and should work correctly if Steam is up. (Basically, you were selecting menu option 5 but it was giving you menu option 4).
> 
> What do you get if running this?
> 
> `xdotool search --onlyvisible --name "Steam"`
> 
> > one interesting behavior I found was (If I start flatpak first then steam) and choose steam as default it will work to download mods. However If I open steam first then flatpak second it will not work and lockup. (this happens cause Steam goes offline on the first instance and goes online on the second)
> 
> I'm not sure about this, sounds like it might be out of our control and needs time to synchronize your login state. I know the behavior you are talking about.
> 
> > Toggle options has to match whichever Steam versions is currently Online and has connection.
> 
> I don't think there is a way of programmatically determining this through a third-party program. This is a big ask. It should be the responsibility of the user to properly close out of other instances before doing this sort of thing.
> 
> Out of curiosity, if you have it installed, try running `xprop` and then interactively selecting the Flatpak Steam window by clicking the mouse cursor on it. It should print debug info to the terminal and contain a line like `WM_CLASS(STRING)= "<some name>"`
> 
> `<some name>` should mention Steam and/or Flatpak somewhere. If Flatpak Steam has a uniquely identifiable name like "Steam: Flatpak", then we can target it. But if it's just called "Steam", we may not be able to.

Not sure if important but :
zuku@zuku-PikaOS ~> xdotool search --onlyvisible --name "Steam"
83886113

zuku@zuku-PikaOS ~> xprop
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
WM_NAME(UTF8_STRING) = "Steam"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
_NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):
	                  ░░▒▒▓▓▓▓▒▒░░                  
	               ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░               
	             ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░             
	           ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░           
	          ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒          
	        ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░        
	       ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░       
	      ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░      
	     ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓░     
	     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░    ░░▓▓▓▓▓▓▓     
	    ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒          ▒▓▓▓▓▓▒    
	   ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░     ░░     ▒▓▓▓▓▓░   
	   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒   ░░▒▓▓▓░    ▒▓▓▓▓▓   
	  ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  ░▒▓▒░░▒▓▒░  ░▓▓▓▓▓▒  
	  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  ░▓▒░    ░▓▒   ▒▓▓▓▓▓  
	 ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  ░▓░      ░▓░  ░▓▓▓▓▓░ 
	 ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓   ▓▒        ▒▒  ░▓▓▓▓▓▒ 
	 ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒  ░▓░        ░▓   ▓▓▓▓▓▓ 
	░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  ░▓░        ░▓   ▓▓▓▓▓▓░
	▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒    ▒▒        ▒▒  ░▓▓▓▓▓▓▒
	▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░    ░▓░      ░▓░  ░▓▓▓▓▓▓▒
	▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░      ▒▓░    ░▓▒   ▒▓▓▓▓▓▓▒
	░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒        ▒▓▒▒▒▓▓▒   ░▓▓▓▓▓▓▓▓
	   ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ░▒▒▒▒░    ▓▓▓▓▓▓▓▓▓
	     ░▒▓▓▓▓▓▓▓▓▓▓▓░                   ▒▓▓▓▓▓▓▓▓▓
	        ░▓▓▓▓▓▓▓▓▒                  ░▒▓▓▓▓▓▓▓▓▓▓
	          ░▒▓▓▒░░                ░░▒▓▓▓▓▓▓▓▓▓▓▓▒
	            ░                  ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒
	               ░▒▓▒░         ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒
	                 ░▒▓░       ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░
	                   ▒▓     ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 
	 ▒▒░                ▓░   ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒ 
	 ░▓▓▒░              ▒▒  ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 
	  ▒▓▓▓▒▒            ▒▒ ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒  
	  ░▓▓▓▓▓▓▒          ▒░ ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  
	   ▒▒▒▒▒▒▓░        ░▓  ▒▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒   
	   ░▒▒▒▒▒▓▒  ▒▒░ ░▒▓░ ░▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░   
	    ▒▒▒▒▒▒▓░  ░▒▒▒▒░  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒    
	     ▒▒▒▒▒▒▒░        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒     
	     ░▒▒▒▒▒▒▒▒░   ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░     
	      ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░      
	       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░       
	        ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░        
	          ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒          
	           ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░           
	             ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░             
	               ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░               
	                  ░░░▒▒▒▒▒▒░░░                  


_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
WM_CLASS(STRING) = "Steam", "Steam"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 1920, 0
		user specified size: 1920 by 1032
		program specified minimum size: 1010 by 600

**Comment by Zukureneno** [comment]
I get this if flatpak is open alone:
zuku@zuku-PikaOS ~> xdotool search --onlyvisible --name "Steam"
94371873

**Comment by Zukureneno** [comment]
> > zuku@zuku-PikaOS ~ [SIGTERM]> ./dzgui.sh
> > [DZGUI] Checking response time of servers
> > /home/zuku/dzgui.sh: line 386: flatpak run com.valvesoftware.Steam: command not found
> > Got this when trying to download mods (flatpak steam open alone+flatpak is toggled)
> 
> This is fixed now, was related to word splitting due to the command consisting of multiple arguments. It was being treated as a single command.

I can confirm if I got flatpak open alone + flatpak toggle option on it will not open regular steam :100:

**Comment by Zukureneno** [comment]
> > ok the msg is not there with latest rc.5 (it was with rc.4; I was testing at the same time as you pushed the update lol)
> 
> I'm still curious about this message, because it's used by another process and should work correctly if Steam is up. (Basically, you were selecting menu option 5 but it was giving you menu option 4).
Just to confirm the msg doesn't appear on Rc.6 so that's fixed (i got both flatpak and regular on the background)

**Comment by aclist** [comment]
Everything seems fine here. I'd say always make sure Steam is running before DZGUI for a better outcome. We don't explicitly check if Steam is running when DZGUI launches because a) it's not the responsibility of the application and b) Steam doesn't provide really clear and unequivocal information that it is open besides a window called "Steam" (which could apply to anything else with Steam in the title, such as a web browser tab or folder, causing collisions).

And don't mix and match different Steam versions at the same time. Also, the preferred setting will only take effect if that version is in fact installed. So if you set Flatpak as preferred but uninstall Flatpak and only have native Steam, it will still gracefully revert to using native Steam. (Preference option is just a best-effort preference)

I think this should be OK now, sorry about the unforeseen bugs; I didn't realize the full ramifications of what you were asking for when I quickly patched it at first.

**Comment by Zukureneno** [comment]
I just tested for the lols @aclist 

Scenario #1
- Flatpak : No connection
- Regular - Connected/online
-Toggled - Flatpak

Joined modded server. It pop open on regular steam to the workshops. Downloaded and all. 
Game launched from Flatpak ; woot (now obviously for obvious reasons it has no connection so it error out)
![image](https://user-images.githubusercontent.com/60487234/213553283-f775b6d5-682e-432c-94fd-d71469a652b7.png)

Scenario #2 Opposite scenario :
- Flatpak : Online
- Regular - Offline
-Toggled - Steam

Stays searching mods forever.

Scenario #3:
-Flatpak : online
-Regular : offline
- Toggled: flatpak 

Works as it should.

Scenario #4 
-Flatpak : Offline
-Regular : Online
-Toggled: Regular Steam

Works as it should.

Can we call this a win? 
Cheers mate thanks for all the help honestly :heart:

**Comment by Zukureneno** [comment]
> Everything seems fine here. I'd say always make sure Steam is running before DZGUI for a better outcome. We don't explicitly check if Steam is running when DZGUI launches because a) it's not the responsibility of the application and b) Steam doesn't provide really clear and unequivocal information that it is open besides a window called "Steam" (which could apply to anything else with Steam in the title, such as a web browser tab or folder, causing collisions).
> 
> And don't mix and match different Steam versions at the same time. Also, the preferred setting will only take effect if that version is in fact installed. So if you set Flatpak as preferred but uninstall Flatpak and only have native Steam, it will still gracefully revert to using native Steam. (Preference option is just a best-effort preference)
> 
> I think this should be OK now, sorry about the unforeseen bugs; I didn't realize the full ramifications of what you were asking for when I quickly patched it at first.

dude its amazing the work you did in 1 day. Crazy honestly and i don't know if you saw my last msg but everything seems to be working

**Comment by aclist** [comment]
> Can we call this a win?

That is looking good, thanks for testing all this. I will keep my ear to the ground and see if this feature misbehaves in the coming days. If you have any problems, feel free to open a new ticket.

Is it customary to have both versions of Steam open, or is that just your preference?

**Comment by Zukureneno** [comment]
> > Can we call this a win?
> 
> That is looking good, thanks for testing all this. I will keep my ear to the ground and see if this feature misbehaves in the coming days. If you have any problems, feel free to open a new ticket.
> 
> Is it customary to have both versions of Steam open, or is that just your preference?

no not at all. It was part of the testing since we were testing the toggle button. 

One of the consequences of having both steams versions installed at the same time on the same session is that it did not know which one to target so it was opening the wrong one even while having one already pre-opened and pre-selected on the toggle.

ex. Had flatpak steam open, toggle was on flatpak = Opened regular steam and try to launch from there. and if you did not have all the mods it bugged out and lock steam up. Did not matter if i close and open it again it stayed bugged.

so yeah sorry about that. That question of having 2 steams installed on 1 machine open a big can of worms. 
1 scenario that this can happen is that some games actually work better on flatpak and viseversa same as having steam installed under lutris or bottles can actually benefit non working proton games. 

One game that had that benefit when it came out was V Rising (was working on bottles and lutris but it was broken on proton)

So yeah that's legit the only scenario I can see someone having multiple versions. 

Does that answer your question?

**Comment by aclist** [comment]
Yes, makes perfect sense, thank you.

**Comment by Zukureneno** [comment]
> Yes, makes perfect sense, thank you.

well I imagine it has been transfer to stable so I'm going to close the issue. Will submit new ones if I find any issues but ***knocks on wood*** hopefully that won't be needed.

Cheers and thanks again for all the help and for this amazing mod loader

**Comment by aclist** [comment]
> well I imagine it has been transfer to stable so I'm going to close the issue. 

Both branches are currently synchronized with each other. Testing will start gearing up for the next release (3.3.0), nothing add yet. Thanks.
