### ISSUE TITLE
[BUG] When max map count isn't set, script erroneously tries to leverage Flatpak

### ISSUE THREAD

**Issue by bongjutsu** [aclist/dztui#57]
Today when running dztui/dzgui, it prompted me to set vm.max_map_count - I declined as I use an external script for this. In the past when I've declined this dialog, dzgui would just continue without a concern. Today however after declining the dialog, I then get this line in the terminal:

`./dzgui.sh: line 1787: flatpak: command not found`

I don't have flatpak on my system, I'm using the steam contained in the Arch repos so I'm not sure why it's trying to call flatpak here. I ran my external max_map_count script and then relaunched dzgui and the issue didn't happen, so it only seems to happen when max_map_count is not set.

**Comment by bongjutsu** [comment]
Update: When max map count is set, I still get the error in terminal, but the script still continues. When it's not set, and I decline, the script terminates.

**Comment by aclist** [comment]
Hi, thanks for the report. This was actually three bugs, that were orthogonal to each other.

1. Last month, a user asked for flatpak Steam support to be added. This was working, but the pre-launch check (whether to fallback to native Steam or flatpak Steam) was supposed to silently suppress errors if one or the other was not found. This was leaking into the terminal but was not the cause of any bugs per se. Not related to the map count issue. This is fixed.
2. When selecting No for map count, the map count dialog was killing the outer dialog responsible for the whole initial setup pipeline and exiting the application. This is fixed.
3. The map count value was being updated into a sysctl file called `dayz.conf` but was not getting reloaded on the fly, so the map count would only be updated on a subsequent reboot. This is fixed as well.

**Comment by bongjutsu** [comment]
These particular issues seem to be resolved with the hotfix so I'm closing this issue
