### ISSUE TITLE
Duplicated Servers on "My Servers" List

### ISSUE THREAD

**Issue by MatheusLasserre** [aclist/dztui#68]
I guess that this happens when i add more than one server under the same ip, but with different ports.

I don't know how they are being saved, but is there a way for edit the ip file?

Another info is that when the dialog starts pinging the server, it counts with the repeated one.

Eg. I have 5 server, 3 of them duplicated. It pings "8" servers

If i can give you any more info or help with something, just let me know

**Comment by MatheusLasserre** [comment]
Just checked the file where the servers id's are being stored, and they're not duplicated there

**Comment by aclist** [comment]
Thanks for the ticket. Interesting problem. Off the top of my head, I can conceptualize how this might occur, but can you give me the exact IDs/IPs so that I can reproduce it exactly?

I tried the below:

https://www.battlemetrics.com/servers/dayz/20897599
https://www.battlemetrics.com/servers/dayz/18159335

Same IP, different IDs, different ports. I added both IDs to My Servers and they only get shown once each (total of 2 servers).

**Comment by MatheusLasserre** [comment]
I remember that it occurred after i added more than 5 or something. Like, one moment it was fine, then this started. Is it better if a give you my list of ids?

#Comma-separated list of server IDs
whitelist="20391344,20391349,20391345,16091212,16091215,18143930,16913178,16918251,18767953,20753070,13399676,8039514,8039512"

**Comment by aclist** [comment]
> I remember that it occurred after i added more than 5 or something. Like, one moment it was fine, then this started. 

Makes sense, that was my suspicion. I think there is a breakpoint here where it is looping over the array at a certain point.

The list is helpful, will test that and report back.

**Comment by aclist** [comment]
It should be fixed in the latest version (stable branch). I also made the transition of the progress dialog smoother so that it triggers immediately after opening My Servers, rather than pausing and showing up after the pings start.

**Comment by MatheusLasserre** [comment]
It's perfect! Thanks for fixing it and also thank you for this software it's REALLY amazing, made my life way easier!

**Comment by aclist** [comment]
Thanks for the kind words! There's always room to make the experience smoother.
