### ISSUE TITLE
"Steam must be running to use this feature" after returning to game after a few weeks.

### ISSUE THREAD

**Issue by GKourp** [aclist/dztui#73]
Greetings! I'll open dzgui, and navigate to the server of my choosing with no issue. When I try to connect to a server it takes a few seconds but then the error appears. DZGUI version is 3.3.2 and I'm on the stable branch.

Edit: I was launching it in desktop mode exclusively. I launched it in gaming mode and it worked.

Edit 2: Returned to desktop mode and DayZ launched normally. Will close ticket.

**Comment by aclist** [comment]
Alright, thanks for the update. I will try to reproduce the issue to see if it is a transitory thing or something deeper. If you encounter problems again, please don't hesitate to open a new ticket.
