### ISSUE TITLE
python version issues

### ISSUE THREAD

**Issue by 10ked** [aclist/dztui#96]
whenever i run dzgui whether in slackware 15 or slackware current
i always get this response:
Requires python >=3.10
then the application closes.

**Comment by aclist** [comment]
What version of python do you have installed? (`python3 --version`)

**Comment by aclist** [comment]
I checked the Slackware project's package database against Slackware Current and Slackware 15: the highest version of Python being shipped in either is Python 3.9. This is too far behind the minimum dependency required for DZGUI.

If your distribution does not provide up to date versions of Python or you cannot compile a newer version of Python from source, I suggest creating a virtual environment and installing a higher version of Python using pip inside of there: https://slackbuilds.org/repository/15.0/python/python3-virtualenv/

Note that when subsequently launching DZGUI, you'll have to enable this virtual environment to make sure it is activated and sourcing the right libraries. There are various wrapper scripts, such as virtualenvwrapper, provided for activating and enabling venvs on the fly. Ideally, you would make a shell script that sources the venv and then launches DZGUI accordingly.

Slackware ships with very few packages out of the box, so adding separate packages is at the user's own discretion.

**Comment by 10ked** [comment]
or i could try to install an up to date python version in the /opt directory and set the PATH properly
to see it so i wouldn't have to use python3-virtualenv which i tried and found it to be more convoluted.
So we shall see if that works next.

**Comment by 10ked** [comment]
Ok i managed to install a new version as mentioned and this worked.
Of course i had to set the $PATH and the /etc/ld.so.conf library path.

**Comment by aclist** [comment]
Thank you for the follow-up. This information has been noted and will be added into a subsequent DZGUI knowledge base article.

**Comment by aclist** [comment]
Please also note that the new major version update releasing today requires PyGObject (python3-gobject) as a necessary dependency.

**Comment by 10ked** [comment]
aand if you DON'T have pip installed in your python version you cannot install PyGObject.

**Comment by aclist** [comment]
Yes, pip is the canonical method of installing Python packages unless the distribution bundles them upstream.
