### ISSUE TITLE
Stuck querying

### ISSUE THREAD

**Issue by djcoppertop** [aclist/dztui#99]
GLibLog: domain:Gtk  msg:gtk_disable_setlocale() must be called before gtk_init()GLibLog: domain:Gtk  msg:gtk_disable_setlocale() must be called before gtk_init()GLibLog: domain:Gtk  msg:gtk_disable_setlocale() must be called before g

Boots to steam and this is whats in console.

**Comment by aclist** [comment]
I need more information:

- Linux distribution and kernel version
- Desktop computer or Steam Deck
- Steam version
- Output of system info log (`Options > Output system info to log file`) -- attach as a file here
- Entire output of debug log immediately after the error occurs (`$HOME/.local/state/dzgui/logs/DZGUI_DEBUG.log`) -- attach as a file here

- When this behavior occurs
    - After selecting a server?
    - When starting the application?
    
 - What console
    - The Steam dev console?
    - The system terminal?
    
- Whether mod install mode is set to auto or manual

**Comment by aclist** [comment]
Closed due to inactivity
